# Project
group=com.github.glitchfiend
release_channel=beta

# Common
minecraft_version=26.3
common_runs_enabled=false
common_client_run_name=Common Client
common_server_run_name=Common Server

# Forge
## forge_version -> https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=66.0.2
forge_version_range=[66.0.2,)
forge_loader_version_range=[66,)

# NeoForge
## neoforge_version -> https://neoforged.net/
## neo_form_version -> https://projects.neoforged.net/neoforged/neoform
neoforge_version=26.3.0.7-beta
neoforge_version_range=[26.3,)
neoforge_loader_version_range=[1,)
neo_form_version=26.3-1

# Fabric
## fabric_version -> https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/all
## fabric_loader_version -> https://github.com/FabricMC/fabric-loader/releases
fabric_version=0.161.0+26.3
fabric_loader_version=0.19.5

# Mod options
mod_id=biomesoplenty
mod_name=BiomesOPlenty
mod_display_name=Biomes O' Plenty
mod_authors=Adubbz, Forstride
mod_description=Adds over 50 new biomes, blocks, and more!
mod_license=All Rights Reserved
mod_page_url=https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty
mod_issues_url=https://github.com/Glitchfiend/BiomesOPlenty/issues
mod_git_url=https://github.com/Glitchfiend/BiomesOPlenty
mod_scm_url=scm:git:git@github.com:Glitchfiend/BiomesOPlenty.git
mod_discord_url=https://discord.gg/GyyzU6T
mod_curseforge_id=220318
mod_modrinth_id=biomes-o-plenty

# Gradle
org.gradle.daemon=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.configuration-cache=false
org.gradle.configuration-cache.parallel=true
org.gradle.configuration-cache.problems=warn

# Forge configuration
net.minecraftforge.gradle.merge-source-sets=true

# Dependencies
nightconfig_version=3.6.7
glitchcore_version=26.3.0.0.0
terrablender_version=26.3.0.0.0
