# Project
group=com.github.glitchfiend
release_channel=beta

# Common
minecraft_version=26.1.2

# Forge
forge_version=64.0.4
forge_version_range=[62.0.0,)
forge_loader_version_range=[62,)

# NeoForge
## neo_form_version -> From https://projects.neoforged.net/neoforged/neoform
neoforge_version=26.1.2.12-beta
neoforge_version_range=[26.1,)
neoforge_loader_version_range=[1,)
neo_form_version=26.1.2-1

# Fabric
fabric_version=0.146.0+26.1.2
fabric_loader_version=0.19.2
# Mod options
mod_id=biomesoplenty
mod_name=BiomesOPlenty
mod_display_name=Biomes O' Plenty
mod_authors=Adubbz, Forstride
mod_description=Adds over 50 new biomes, blocks, and more!
mod_license=All Rights Reserved
mod_page_url=https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty
mod_issues_url=https://github.com/Glitchfiend/BiomesOPlenty/issues
mod_git_url=https://github.com/Glitchfiend/BiomesOPlenty
mod_scm_url=scm:git:git@github.com:Glitchfiend/BiomesOPlenty.git
mod_discord_url=https://discord.gg/GyyzU6T
mod_curseforge_id=220318
mod_modrinth_id=biomes-o-plenty

# Gradle
org.gradle.daemon=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.configuration-cache=false
org.gradle.configuration-cache.parallel=true
org.gradle.configuration-cache.problems=warn

# Forge configuration
net.minecraftforge.gradle.merge-source-sets=true

# Dependencies
nightconfig_version=3.6.7
glitchcore_version=26.1.2.0.0
terrablender_version=26.1.2.0.1
