// Date: 10/26/2013 6:50:10 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelWasp extends ModelBase
{
  //fields
    ModelRenderer Body;
    ModelRenderer Body;
    ModelRenderer Stinger;
    ModelRenderer Left_Leg;
    ModelRenderer Left_Leg;
    ModelRenderer Left_Leg;
    ModelRenderer Right_Leg;
    ModelRenderer Right_Leg;
    ModelRenderer Right_Leg;
    ModelRenderer Left_Wing;
    ModelRenderer Right_Wing;
    ModelRenderer Head;
    ModelRenderer Head;
    ModelRenderer Antenna;
    ModelRenderer Antenna;
  
  public ModelBee()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Body = new ModelRenderer(this, 0, 0);
      Body.addBox(0F, 0F, 0F, 5, 5, 8);
      Body.setRotationPoint(0F, 0F, 0F);
      Body.setTextureSize(64, 32);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      Body = new ModelRenderer(this, 0, 13);
      Body.addBox(0F, 0F, 0F, 3, 3, 2);
      Body.setRotationPoint(1F, 2F, -2F);
      Body.setTextureSize(64, 32);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      Stinger = new ModelRenderer(this, 0, 18);
      Stinger.addBox(0F, 0F, 0F, 1, 1, 3);
      Stinger.setRotationPoint(2F, 4F, -5F);
      Stinger.setTextureSize(64, 32);
      Stinger.mirror = true;
      setRotation(Stinger, 0F, 0F, 0F);
      Left_Leg = new ModelRenderer(this, 13, 23);
      Left_Leg.addBox(0F, 0F, 0F, 1, 4, 1);
      Left_Leg.setRotationPoint(-1F, 4F, 1F);
      Left_Leg.setTextureSize(64, 32);
      Left_Leg.mirror = true;
      setRotation(Left_Leg, 0F, 0F, 0F);
      Left_Leg = new ModelRenderer(this, 13, 23);
      Left_Leg.addBox(0F, 0F, 0F, 1, 3, 1);
      Left_Leg.setRotationPoint(-1F, 4F, 4F);
      Left_Leg.setTextureSize(64, 32);
      Left_Leg.mirror = true;
      setRotation(Left_Leg, 0F, 0F, 0F);
      Left_Leg = new ModelRenderer(this, 13, 23);
      Left_Leg.addBox(0F, 0F, 0F, 1, 4, 1);
      Left_Leg.setRotationPoint(-1F, 4F, 6F);
      Left_Leg.setTextureSize(64, 32);
      Left_Leg.mirror = true;
      setRotation(Left_Leg, 0F, 0F, 0F);
      Right_Leg = new ModelRenderer(this, 13, 23);
      Right_Leg.addBox(0F, 0F, 0F, 1, 4, 1);
      Right_Leg.setRotationPoint(5F, 4F, 1F);
      Right_Leg.setTextureSize(64, 32);
      Right_Leg.mirror = true;
      setRotation(Right_Leg, 0F, 0F, 0F);
      Right_Leg = new ModelRenderer(this, 13, 23);
      Right_Leg.addBox(0F, 0F, 0F, 1, 3, 1);
      Right_Leg.setRotationPoint(5F, 4F, 4F);
      Right_Leg.setTextureSize(64, 32);
      Right_Leg.mirror = true;
      setRotation(Right_Leg, 0F, 0F, 0F);
      Right_Leg = new ModelRenderer(this, 13, 23);
      Right_Leg.addBox(0F, 0F, 0F, 1, 4, 1);
      Right_Leg.setRotationPoint(5F, 4F, 6F);
      Right_Leg.setTextureSize(64, 32);
      Right_Leg.mirror = true;
      setRotation(Right_Leg, 0F, 0F, 0F);
      Left_Wing = new ModelRenderer(this, 24, 26);
      Left_Wing.addBox(0F, 0F, 0F, 8, 1, 5);
      Left_Wing.setRotationPoint(-7F, -1F, 2F);
      Left_Wing.setTextureSize(64, 32);
      Left_Wing.mirror = true;
      setRotation(Left_Wing, 0F, 0F, 0F);
      Right_Wing = new ModelRenderer(this, 24, 20);
      Right_Wing.addBox(0F, 0F, 0F, 8, 1, 5);
      Right_Wing.setRotationPoint(4F, -1F, 2F);
      Right_Wing.setTextureSize(64, 32);
      Right_Wing.mirror = true;
      setRotation(Right_Wing, 0F, 0F, 0F);
      Head = new ModelRenderer(this, 46, 0);
      Head.addBox(0F, 0F, 0F, 5, 5, 4);
      Head.setRotationPoint(0F, -2F, 8F);
      Head.setTextureSize(64, 32);
      Head.mirror = true;
      setRotation(Head, 0F, 0F, 0F);
      Head = new ModelRenderer(this, 54, 9);
      Head.addBox(0F, 0F, 0F, 3, 4, 2);
      Head.setRotationPoint(1F, 0F, 11F);
      Head.setTextureSize(64, 32);
      Head.mirror = true;
      setRotation(Head, 0F, 0F, 0F);
      Antenna = new ModelRenderer(this, 54, 27);
      Antenna.addBox(0F, 0F, 0F, 1, 1, 4);
      Antenna.setRotationPoint(1F, -3F, 10F);
      Antenna.setTextureSize(64, 32);
      Antenna.mirror = true;
      setRotation(Antenna, 0F, 0F, 0F);
      Antenna = new ModelRenderer(this, 54, 27);
      Antenna.addBox(0F, 0F, 0F, 1, 1, 4);
      Antenna.setRotationPoint(3F, -3F, 10F);
      Antenna.setTextureSize(64, 32);
      Antenna.mirror = true;
      setRotation(Antenna, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Body.render(f5);
    Body.render(f5);
    Stinger.render(f5);
    Left_Leg.render(f5);
    Left_Leg.render(f5);
    Left_Leg.render(f5);
    Right_Leg.render(f5);
    Right_Leg.render(f5);
    Right_Leg.render(f5);
    Left_Wing.render(f5);
    Right_Wing.render(f5);
    Head.render(f5);
    Head.render(f5);
    Antenna.render(f5);
    Antenna.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
