plugins {
    id 'net.minecraftforge.gradle' version '[7.0.17,8)'
    id "de.maxhenkel.cursegradle" version "1.5.1"
}

base.archivesName.set("${mod_name}-forge")

minecraft {
    mappings channel: 'official', version: minecraft_version
    accessTransformers = files(project(":Common").file('src/main/resources/META-INF/accesstransformer.cfg'))

    runs {
        configureEach {
            workingDir = layout.projectDirectory.dir('run')

            systemProperty 'eventbus.api.strictRuntimeChecks', 'true'
            systemProperty 'forge.enabledGameTestNamespaces', 'examplemod'
        }

        register('client') {
            args "-mixin.config=${mod_id}.mixins.json", "-mixin.config=${mod_id}.forge.mixins.json"
        }

        register('server') {
            args '--nogui', "-mixin.config=${mod_id}.mixins.json", "-mixin.config=${mod_id}.forge.mixins.json"
        }
    }
}

jar {
    manifest {
        attributes([
                'MixinConfigs': "${mod_id}.mixins.json" + "," + "${mod_id}.forge.mixins.json",
        ])
    }
}

configurations {
    shade
    implementation.extendsFrom shade
}

sourceSets.main.resources.srcDir 'src/generated/resources'

repositories {
    minecraft.mavenizer(it) // In Kotlin, it = this
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
    mavenCentral()
}

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${minecraft_version}-${forge_version}")
    implementation 'com.github.glitchfiend:GlitchCore-forge:' + minecraft_version + '-' + glitchcore_version
    implementation 'com.github.glitchfiend:TerraBlender-forge:' + minecraft_version + '-' + terrablender_version
    annotationProcessor 'org.spongepowered:mixin:0.8.7:processor'
}

curseforge {
    apiKey = project.findProperty('curseApiKey') ?: 'unset'
    project {
        id = mod_curseforge_id

        if (changelog_file.exists()) {
            changelog = changelog_file
        }

        releaseType = release_channel
        addGameVersion minecraft_version
        addGameVersion name

        mainArtifact(jar) {
            displayName = "${mod_display_name} ${name} ${version}"
        }
    }
}
