package tdwp_ftw.biomesop.configuration;

import java.io.File;
import java.util.logging.Level;

import net.minecraftforge.common.Configuration;
import tdwp_ftw.biomesop.ClientProxy;
import tdwp_ftw.biomesop.mod_BiomesOPlenty;
import cpw.mods.fml.common.FMLLog;

public class BOPConfiguration {

	public static Configuration config;
	
	// Configuration variables
	public static boolean skyColors;
	public static int biomeSize;
	public static boolean addToDefault;
	public static boolean achievements;
	public static boolean vanillaEnhanced;
	public static int promisedLandDimID;

	public static boolean alpsGen;
	public static boolean arcticGen;
	public static boolean badlandsGen;
	public static boolean bambooForestGen;
	public static boolean bayouGen;
	public static boolean birchForestGen;
	public static boolean bogGen;
	public static boolean borealForestGen;
	public static boolean canyonGen;
	public static boolean chaparralGen;
	public static boolean cherryBlossomGroveGen;
	public static boolean coniferousForestGen;
	public static boolean cragGen;
	public static boolean deadForestGen;
	public static boolean deadSwampGen;
	public static boolean deadlandsGen;
	public static boolean deciduousForestGen;
	public static boolean drylandsGen;
	public static boolean dunesGen;
	public static boolean fenGen;
	public static boolean fieldGen;
	public static boolean frostForestGen;
	public static boolean fungiForestGen;
	public static boolean gardenGen;
	public static boolean glacierGen;
	public static boolean grasslandGen;
	public static boolean groveGen;
	public static boolean heathlandGen;
	public static boolean highlandGen;
	public static boolean iceSheetGen;
	public static boolean icyHillsGen;
	public static boolean jadeCliffsGen;
	public static boolean lushDesertGen;
	public static boolean lushSwampGen;
	public static boolean mangroveGen;
	public static boolean mapleWoodsGen;
	public static boolean marshGen;
	public static boolean meadowGen;
	public static boolean mesaGen;
	public static boolean moorGen;
	public static boolean mountainGen;
	public static boolean mushroomIslandGen;
	public static boolean mysticGroveGen;
	public static boolean oasisGen;
	public static boolean ominousWoodsGen;
	public static boolean orchardGen;
	public static boolean originValleyGen;
	public static boolean outbackGen;
	public static boolean pastureGen;
	public static boolean prairieGen;
	public static boolean quagmireGen;
	public static boolean rainforestGen;
	public static boolean redwoodForestGen;
	public static boolean sacredSpringsGen;
	public static boolean savannaGen;
	public static boolean scrublandGen;
	public static boolean seasonalForestGen;
	public static boolean shieldGen;
	public static boolean shrublandGen;
	public static boolean snowyWoodsGen;
	public static boolean spruceWoodsGen;
	public static boolean steppeGen;
	public static boolean swampwoodsGen;
	public static boolean temperateRainforestGen;
	public static boolean thicketGen;
	public static boolean tropicalRainforestGen;
	public static boolean tropicsGen;
	public static boolean tundraGen;
	public static boolean volcanoGen;
	public static boolean wastelandGen;
	public static boolean wetlandGen;
	public static boolean woodlandGen;

	public static boolean plainsGen;
	public static boolean desertGen;
	public static boolean extremeHillsGen;
	public static boolean forestGen;
	public static boolean taigaGen;
	public static boolean swamplandGen;
	public static boolean jungleGen;

	public static int mudID;
	public static int driedDirtID;
	public static int redRockID;
	public static int ashID;
	public static int deadGrassID;
	public static int desertGrassID;
	public static int whiteFlowerID;
	public static int blueFlowerID;
	public static int purpleFlowerID;
	public static int orangeFlowerID;
	public static int tinyFlowerID;
	public static int glowFlowerID;
	public static int cattailID;
	public static int willowID;
	public static int autumnLeavesID;
	public static int thornID;
	public static int toadstoolID;
	public static int highGrassBottomID;
	public static int highGrassTopID;
	public static int ashStoneID;
	public static int hardIceID;
	public static int redLeavesID;
	public static int orangeLeavesID;
	public static int pinkLeavesID;
	public static int blueLeavesID;
	public static int whiteLeavesID;
	public static int deadLeavesID;
	public static int shortGrassID;
	public static int appleLeavesID;
	public static int sproutID;
	public static int bushID;
	public static int bambooID;
	public static int bambooLeavesID;
	public static int mudBrickBlockID;
	public static int mudBrickDoubleSlabID;
	public static int mudBrickSingleSlabID;
	public static int mudBrickStairsID;
	public static int originGrassID;
	public static int originLeavesID;
	public static int pinkFlowerID;
	public static int treeMossID;
	public static int deadWoodID;
	public static int appleLeavesFruitlessID;
	public static int barleyID;
	public static int giantFlowerStemID;
	public static int giantFlowerRedID;
	public static int giantFlowerYellowID;
	public static int tinyCactusID;
	public static int firSaplingID;
	public static int redwoodSaplingID;
	public static int palmSaplingID;
	public static int redSaplingID;
	public static int orangeSaplingID;
	public static int yellowSaplingID;
	public static int brownSaplingID;
	public static int willowSaplingID;
	public static int appleSaplingID;
	public static int originSaplingID;
	public static int pinkSaplingID;
	public static int whiteSaplingID;
	public static int darkSaplingID;
	public static int magicSaplingID;
	public static int deathbloomID;
	public static int redRockCobbleID;
	public static int redRockCobbleDoubleSlabID;
	public static int redRockCobbleSingleSlabID;
	public static int redRockCobbleStairsID;
	public static int redRockBrickID;
	public static int redRockBrickDoubleSlabID;
	public static int redRockBrickSingleSlabID;
	public static int redRockBrickStairsID;
	public static int hydrangeaID;
	public static int violetID;
	public static int mediumGrassID;
	public static int duneGrassID;
	public static int desertSproutsID;
	public static int mangroveSaplingID;
	public static int hardSandID;
	public static int acaciaSaplingID;
	public static int hardDirtID;
	public static int holyGrassID;
	public static int holyStoneID;
	public static int holyTallGrassID;
	public static int promisedLandPortalID;
	public static int holySaplingID;
	public static int amethystOreID;
	public static int amethystBlockID;
	public static int bambooThatchingID;
	public static int mossID;
	public static int algaeID;
	public static int smolderingGrassID;
	public static int cragRockID;
	public static int quicksandID;
	public static int bambooSaplingID;

	//Redwood
	public static int redwoodPlankID;
	public static int redwoodWoodID;
	public static int redwoodLeavesID;
	public static int redwoodDoubleSlabID;
	public static int redwoodSingleSlabID;
	public static int redwoodStairsID;

	//Willow
	public static int willowPlankID;
	public static int willowWoodID;
	public static int willowLeavesID;
	public static int willowDoubleSlabID;
	public static int willowSingleSlabID;
	public static int willowStairsID;

	//Fir
	public static int firPlankID;
	public static int firWoodID;
	public static int firLeavesID;
	public static int firDoubleSlabID;
	public static int firSingleSlabID;
	public static int firStairsID;

	//Acacia
	public static int acaciaPlankID;
	public static int acaciaWoodID;
	public static int acaciaLeavesID;
	public static int acaciaDoubleSlabID;
	public static int acaciaSingleSlabID;
	public static int acaciaStairsID;

	//Cherry
	public static int cherryPlankID;
	public static int cherryWoodID;
	public static int cherryDoubleSlabID;
	public static int cherrySingleSlabID;
	public static int cherryStairsID;

	//Dark
	public static int darkPlankID;
	public static int darkWoodID;
	public static int darkLeavesID;
	public static int darkDoubleSlabID;
	public static int darkSingleSlabID;
	public static int darkStairsID;

	//Magic
	public static int magicPlankID;
	public static int magicWoodID;
	public static int magicDoubleSlabID;
	public static int magicSingleSlabID;
	public static int magicStairsID;

	//Palm
	public static int palmPlankID;
	public static int palmWoodID;
	public static int palmLeavesID;
	public static int palmDoubleSlabID;
	public static int palmSingleSlabID;
	public static int palmStairsID;

	//Mangrove
	public static int mangrovePlankID;
	public static int mangroveWoodID;
	public static int mangroveLeavesID;
	public static int mangroveDoubleSlabID;
	public static int mangroveSingleSlabID;
	public static int mangroveStairsID;

	//Holy
	public static int holyPlankID;
	public static int holyWoodID;
	public static int holyLeavesID;
	public static int holyDoubleSlabID;
	public static int holySingleSlabID;
	public static int holyStairsID;

	public static int shroomPowderID;
	public static int mudBallID;
	public static int mudBrickID;
	public static int cattailItemID;
	public static int bambooItemID;
	public static int barleyItemID;
	public static int shortGrassItemID;
	public static int mediumGrassItemID;
	public static int bushItemID;
	public static int sproutItemID;
	public static int mossItemID;
	public static int ashesID;
	public static int ancientStaffID;
	public static int ancientStaffHandleID;
	public static int ancientStaffPoleID;
	public static int ancientStaffTopperID;
	public static int enderporterID;
	public static int bopDiscID;
	public static int bopDiscMudID;
	public static int swordMudID;
	public static int shovelMudID;
	public static int pickaxeMudID;
	public static int axeMudID;
	public static int hoeMudID;
	public static int helmetMudID;
	public static int chestplateMudID;
	public static int leggingsMudID;
	public static int bootsMudID;
	public static int amethystID;
	public static int swordAmethystID;
	public static int shovelAmethystID;
	public static int pickaxeAmethystID;
	public static int axeAmethystID;
	public static int hoeAmethystID;
	public static int helmetAmethystID;
	public static int chestplateAmethystID;
	public static int leggingsAmethystID;
	public static int bootsAmethystID;

	public static int alpsID;
	public static int arcticID;
	public static int arcticForestID;
	public static int badlandsID;
	public static int bambooForestID;
	public static int bayouID;
	public static int birchForestID;
	public static int bogID;
	public static int borealForestID;
	public static int canyonID;
	public static int chaparralID;
	public static int cherryBlossomGroveID;
	public static int coniferousForestID;
	public static int coniferousForestThinID;
	public static int cragID;
	public static int deadForestID;
	public static int deadSwampID;
	public static int deadlandsID;
	public static int deciduousForestID;
	public static int drylandsID;
	public static int dunesID;
	public static int fenID;
	public static int fieldID;
	public static int frostForestID;
	public static int fungiForestID;
	public static int gardenID;
	public static int glacierID;
	public static int grasslandID;
	public static int groveID;
	public static int groveThinID;
	public static int heathlandID;
	public static int highlandID;
	public static int iceSheetID;
	public static int icyHillsID;
	public static int jadeCliffsID;
	public static int lushDesertID;
	public static int lushSwampID;
	public static int mangroveID;
	public static int mapleWoodsID;
	public static int marshID;
	public static int meadowID;
	public static int meadowForestID;
	public static int mesaID;
	public static int moorID;
	public static int mountainID;
	public static int mysticGroveID;
	public static int oasisID;
	public static int ominousWoodsID;
	public static int orchardID;
	public static int originValleyID;
	public static int outbackID;
	public static int pastureID;
	public static int prairieID;
	public static int promisedLandID;
	public static int promisedLandHillsID;
	public static int promisedLandPlainsID;
	public static int promisedLandSwampID;
	public static int quagmireID;
	public static int rainforestID;
	public static int redwoodForestID;
	public static int reefID;
	public static int sacredSpringsID;
	public static int savannaID;
	public static int savannaThickID;
	public static int scrublandID;
	public static int seasonalForestID;
	public static int shieldID;
	public static int shoreID;
	public static int shrublandID;
	public static int snowyWoodsID;
	public static int spruceWoodsID;
	public static int steppeID;
	public static int swampwoodsID;
	public static int temperateRainforestID;
	public static int thicketID;
	public static int tropicalRainforestID;
	public static int tropicsID;
	public static int tundraID;
	public static int tundraDryID;
	public static int volcanoID;
	public static int wastelandID;
	public static int wastelandTreesID;
	public static int wetlandID;
	public static int woodlandID;
	public static int plainsNewID;
	public static int desertNewID;
	public static int desertHillsNewID;
	public static int extremeHillsNewID;
	public static int extremeHillsEdgeNewID;
	public static int forestNewID;
	public static int forestHillsNewID;
	public static int taigaNewID;
	public static int taigaHillsNewID;
	public static int swamplandNewID;
	public static int jungleNewID;
	public static int jungleHillsNewID;

	public static int jungleSpiderID;
	public static int rosesterID;

	public static void init(File configFile) 
	{
		boolean isClient = mod_BiomesOPlenty.proxy instanceof ClientProxy;
		
		config = new Configuration(configFile);

		try 
		{
			config.load();

			skyColors = true;
			biomeSize = config.get("Biome Settings", "Biome Size", 4, null).getInt();
			achievements = config.get("Achievement Settings", "Add Biomes O Plenty Achievemnets (Currently Broken)", false).getBoolean(false);
			vanillaEnhanced = config.get("Biome Settings", "Enhanced Vanilla Biomes", true).getBoolean(false);
			promisedLandDimID = config.get("Dimension Settings", "Promised Land Dimension ID", 20, null).getInt();
			
			if (!isClient)
			{
				addToDefault = config.get("Biome Settings", "Add Biomes To Default World", true).getBoolean(true);
			}
			else
			{
				addToDefault = config.get("Biome Settings", "Add Biomes To Default World", false).getBoolean(false);
			}

			alpsGen = config.get("Biomes To Generate", "Alps", true).getBoolean(false);
			arcticGen = config.get("Biomes To Generate", "Arctic", true).getBoolean(false);
			badlandsGen = config.get("Biomes To Generate", "Badlands", true).getBoolean(false);
			bambooForestGen = config.get("Biomes To Generate", "BambooForest", true).getBoolean(false);
			bayouGen = config.get("Biomes To Generate", "Bayou", true).getBoolean(false);
			birchForestGen = config.get("Biomes To Generate", "BirchForest", true).getBoolean(false);
			bogGen = config.get("Biomes To Generate", "Bog", true).getBoolean(false);
			borealForestGen = config.get("Biomes To Generate", "BorealForest", true).getBoolean(false);
			canyonGen = config.get("Biomes To Generate", "Canyon", true).getBoolean(false);
			chaparralGen = config.get("Biomes To Generate", "Chaparral", true).getBoolean(false);
			cherryBlossomGroveGen = config.get("Biomes To Generate", "CherryBlossomGrove", true).getBoolean(false);
			coniferousForestGen = config.get("Biomes To Generate", "ConiferousForest", true).getBoolean(false);
			cragGen = config.get("Biomes To Generate", "Crag", true).getBoolean(false);
			deadForestGen = config.get("Biomes To Generate", "DeadForest", true).getBoolean(false);
			deadSwampGen = config.get("Biomes To Generate", "DeadSwamp", true).getBoolean(false);
			deadlandsGen = config.get("Biomes To Generate", "Deadlands", true).getBoolean(false);
			deciduousForestGen = config.get("Biomes To Generate", "DeciduousForest", true).getBoolean(false);
			desertGen = config.get("Biomes To Generate", "Desert", true).getBoolean(false);
			drylandsGen = config.get("Biomes To Generate", "Drylands", true).getBoolean(false);
			dunesGen = config.get("Biomes To Generate", "Dunes", true).getBoolean(false);
			extremeHillsGen = config.get("Biomes To Generate", "ExtremeHills", true).getBoolean(false);
			fenGen = config.get("Biomes To Generate", "Fen", true).getBoolean(false);
			fieldGen = config.get("Biomes To Generate", "Field", true).getBoolean(false);
			forestGen = config.get("Biomes To Generate", "Forest", true).getBoolean(false);
			frostForestGen = config.get("Biomes To Generate", "FrostForest", true).getBoolean(false);
			fungiForestGen = config.get("Biomes To Generate", "FungiForest", true).getBoolean(false);
			gardenGen = config.get("Biomes To Generate", "Garden", true).getBoolean(false);
			glacierGen = config.get("Biomes To Generate", "Glacier", true).getBoolean(false);
			grasslandGen = config.get("Biomes To Generate", "Grassland", true).getBoolean(false);
			groveGen = config.get("Biomes To Generate", "Grove", true).getBoolean(false);
			heathlandGen = config.get("Biomes To Generate", "Heathland", true).getBoolean(false);
			highlandGen = config.get("Biomes To Generate", "Highland", true).getBoolean(false);
			iceSheetGen = config.get("Biomes To Generate", "IcySheet", true).getBoolean(false);
			icyHillsGen = config.get("Biomes To Generate", "IcyHills", true).getBoolean(false);
			jadeCliffsGen = config.get("Biomes To Generate", "JadeCliffs", true).getBoolean(false);
			jungleGen = config.get("Biomes To Generate", "Jungle", true).getBoolean(false);
			lushDesertGen = config.get("Biomes To Generate", "LushDesert", true).getBoolean(false);
			lushSwampGen = config.get("Biomes To Generate", "LushSwamp", true).getBoolean(false);
			mangroveGen = config.get("Biomes To Generate", "Mangrove", true).getBoolean(false);
			mapleWoodsGen = config.get("Biomes To Generate", "MapleWoods", true).getBoolean(false);
			marshGen = config.get("Biomes To Generate", "Marsh", true).getBoolean(false);
			meadowGen = config.get("Biomes To Generate", "Meadow", true).getBoolean(false);
			mesaGen = config.get("Biomes To Generate", "Mesa", true).getBoolean(false);
			moorGen = config.get("Biomes To Generate", "Moor", true).getBoolean(false);
			mountainGen = config.get("Biomes To Generate", "Mountain", true).getBoolean(false);
			mushroomIslandGen = config.get("Biomes To Generate", "MushroomIsland", true).getBoolean(false);
			mysticGroveGen = config.get("Biomes To Generate", "MysticGrove", true).getBoolean(false);
			oasisGen = config.get("Biomes To Generate", "Oasis", true).getBoolean(false);
			ominousWoodsGen = config.get("Biomes To Generate", "OminousWoods", true).getBoolean(false);
			orchardGen = config.get("Biomes To Generate", "Orchard", true).getBoolean(false);
			originValleyGen = config.get("Biomes To Generate", "OriginValley", true).getBoolean(false);
			outbackGen = config.get("Biomes To Generate", "Outback", true).getBoolean(false);
			pastureGen = config.get("Biomes To Generate", "Pasture", true).getBoolean(false);
			plainsGen = config.get("Biomes To Generate", "Plains", true).getBoolean(false);
			prairieGen = config.get("Biomes To Generate", "Prairie", true).getBoolean(false);
			quagmireGen = config.get("Biomes To Generate", "Quagmire", true).getBoolean(false);
			rainforestGen = config.get("Biomes To Generate", "Rainforest", true).getBoolean(false);
			redwoodForestGen = config.get("Biomes To Generate", "RedwoodForest", true).getBoolean(false);
			sacredSpringsGen = config.get("Biomes To Generate", "SacredSprings", true).getBoolean(false);
			savannaGen = config.get("Biomes To Generate", "Savanna", true).getBoolean(false);
			scrublandGen = config.get("Biomes To Generate", "Scrubland", true).getBoolean(false);
			seasonalForestGen = config.get("Biomes To Generate", "SeasonalForest", true).getBoolean(false);
			shieldGen = config.get("Biomes To Generate", "Shield", true).getBoolean(false);
			shrublandGen = config.get("Biomes To Generate", "Shrubland", true).getBoolean(false);
			snowyWoodsGen = config.get("Biomes To Generate", "SnowyWoods", true).getBoolean(false);
			spruceWoodsGen = config.get("Biomes To Generate", "SpruceWoods", true).getBoolean(false);
			steppeGen = config.get("Biomes To Generate", "Steppe", true).getBoolean(false);
			swamplandGen = config.get("Biomes To Generate", "Swampland", true).getBoolean(false);
			swampwoodsGen = config.get("Biomes To Generate", "Swampwoods", true).getBoolean(false);
			taigaGen = config.get("Biomes To Generate", "Taiga", true).getBoolean(false);
			temperateRainforestGen = config.get("Biomes To Generate", "TemperateRainforest", true).getBoolean(false);
			thicketGen = config.get("Biomes To Generate", "Thicket", true).getBoolean(false);
			tropicalRainforestGen = config.get("Biomes To Generate", "TropicalRainforest", true).getBoolean(false);
			tropicsGen = config.get("Biomes To Generate", "Tropics", true).getBoolean(false);
			tundraGen = config.get("Biomes To Generate", "Tundra", true).getBoolean(false);
			volcanoGen = config.get("Biomes To Generate", "Volcano", true).getBoolean(false);
			wastelandGen = config.get("Biomes To Generate", "Wasteland", true).getBoolean(false);
			wetlandGen = config.get("Biomes To Generate", "Wetland", true).getBoolean(false);
			woodlandGen = config.get("Biomes To Generate", "Woodland", true).getBoolean(false);

			// Get Terrain Block ID's
			mudID = config.getTerrainBlock("Terrain Block IDs", "Mud ID", 160, null).getInt();
			driedDirtID = config.getTerrainBlock("Terrain Block IDs", "Dried Dirt ID", 161, null).getInt();
			redRockID = config.getTerrainBlock("Terrain Block IDs", "Red Rock ID", 162, null).getInt();
			ashID = config.getTerrainBlock("Terrain Block IDs", "Ash Block ID", 163, null).getInt();
			ashStoneID = config.getTerrainBlock("Terrain Block IDs", "Ash Stone ID", 164, null).getInt();
			hardIceID = config.getTerrainBlock("Terrain Block IDs", "Hard Ice ID", 165, null).getInt();
			originGrassID = config.getTerrainBlock("Terrain Block IDs", "Origin Grass ID", 166, null).getInt();
			hardSandID = config.getTerrainBlock("Terrain Block IDs", "Hard Sand ID", 167, null).getInt();
			hardDirtID = config.getTerrainBlock("Terrain Block IDs", "Hard Dirt ID", 168, null).getInt();
			holyGrassID = config.getTerrainBlock("Terrain Block IDs", "Holy Grass ID", 169, null).getInt();
			holyStoneID = config.getTerrainBlock("Terrain Block IDs", "Holy Stone ID", 170, null).getInt();
			cragRockID = config.getTerrainBlock("Terrain Block IDs", "Crag Rock ID", 171, null).getInt();

			// Get Crafted Block ID's
			mudBrickBlockID = config.getBlock("Mud Bricks ID", 256, null).getInt();
			redwoodPlankID = config.getBlock("Redwood Plank ID", 257, null).getInt();
			redwoodDoubleSlabID = config.getBlock("Redwood Double Slab ID", 258, null).getInt();
			redwoodSingleSlabID = config.getBlock("Redwood Single Slab ID", 259, null).getInt();
			redwoodStairsID = config.getBlock("Redwood Stairs ID", 260, null).getInt();
			willowPlankID = config.getBlock("Willow Plank ID", 261, null).getInt();
			willowDoubleSlabID = config.getBlock("Willow Double Slab ID", 262, null).getInt();
			willowSingleSlabID = config.getBlock("Willow Single Slab ID", 263, null).getInt();
			willowStairsID = config.getBlock("Willow Stairs ID", 264, null).getInt();
			firPlankID = config.getBlock("Fir Plank ID", 265, null).getInt();
			firDoubleSlabID = config.getBlock("Fir Double Slab ID", 266, null).getInt();
			firSingleSlabID = config.getBlock("Fir Single Slab ID", 267, null).getInt();
			firStairsID = config.getBlock("Fir Stairs ID", 268, null).getInt();
			acaciaPlankID = config.getBlock("Acacia Plank ID", 269, null).getInt();
			acaciaDoubleSlabID = config.getBlock("Acacia Double Slab ID", 270, null).getInt();
			acaciaSingleSlabID = config.getBlock("Acacia Single Slab ID", 271, null).getInt();
			acaciaStairsID = config.getBlock("Acacia Stairs ID", 272, null).getInt();
			cherryPlankID = config.getBlock("Cherry Plank ID", 273, null).getInt();
			cherryDoubleSlabID = config.getBlock("Cherry Double Slab ID", 274, null).getInt();
			cherrySingleSlabID = config.getBlock("Cherry Single Slab ID", 275, null).getInt();
			cherryStairsID = config.getBlock("Cherry Stairs ID", 276, null).getInt();
			darkPlankID = config.getBlock("Dark Plank ID", 277, null).getInt();
			darkDoubleSlabID = config.getBlock("Dark Double Slab ID", 278, null).getInt();
			darkSingleSlabID = config.getBlock("Dark Single Slab ID", 279, null).getInt();
			darkStairsID = config.getBlock("Dark Stairs ID", 280, null).getInt();
			magicPlankID = config.getBlock("Magic Plank ID", 281, null).getInt();
			magicDoubleSlabID = config.getBlock("Magic Double Slab ID", 282, null).getInt();
			magicSingleSlabID = config.getBlock("Magic Single Slab ID", 283, null).getInt();
			magicStairsID = config.getBlock("Magic Stairs ID", 284, null).getInt();
			palmPlankID = config.getBlock("Palm Plank ID", 285, null).getInt();
			palmDoubleSlabID = config.getBlock("Palm Double Slab ID", 286, null).getInt();
			palmSingleSlabID = config.getBlock("Palm Single Slab ID", 287, null).getInt();
			palmStairsID = config.getBlock("Palm Stairs ID", 288, null).getInt();
			originLeavesID = config.getBlock("Origin Leaves ID", 289, null).getInt();
			redwoodWoodID = config.getBlock("Redwood Log ID", 290, null).getInt();
			redwoodLeavesID = config.getBlock("Redwood Leaves ID", 291, null).getInt();
			willowWoodID = config.getBlock("Willow Log ID", 292, null).getInt();
			willowLeavesID = config.getBlock("Willow Leaves ID", 293, null).getInt();
			firWoodID = config.getBlock("Fir Log ID", 294, null).getInt();
			firLeavesID = config.getBlock("Fir Leaves ID", 295, null).getInt();
			acaciaWoodID = config.getBlock("Acacia Log ID", 296, null).getInt();
			acaciaLeavesID = config.getBlock("Acacia Leaves ID", 297, null).getInt();
			cherryWoodID = config.getBlock("Cherry Log ID", 298, null).getInt();
			pinkFlowerID = config.getBlock("Pink Flower ID", 299, null).getInt();
			darkWoodID = config.getBlock("Dark Log ID", 300, null).getInt();
			darkLeavesID = config.getBlock("Dark Leaves ID", 301, null).getInt();
			treeMossID = config.getBlock("Tree Moss ID", 302, null).getInt();
			magicWoodID = config.getBlock("Magic Log ID", 303, null).getInt();
			deadWoodID = config.getBlock("Dead Log ID", 304, null).getInt();
			appleLeavesFruitlessID = config.getBlock("Fruitless Apple Leaves ID", 305, null).getInt();
			barleyID = config.getBlock("Barley ID", 306, null).getInt();
			palmWoodID = config.getBlock("Palm Log ID", 307, null).getInt();
			palmLeavesID = config.getBlock("Palm Leaves ID", 308, null).getInt();
			giantFlowerRedID = config.getBlock("Giant Red Flower ID", 309, null).getInt();
			giantFlowerStemID = config.getBlock("Giant Flower Stem ID", 310, null).getInt();
			giantFlowerYellowID = config.getBlock("Giant Yellow Flower ID", 311, null).getInt();
			redLeavesID = config.getBlock("Maple Leaves ID", 312, null).getInt();
			orangeLeavesID = config.getBlock("Orange Autumn Leaves ID", 313, null).getInt();
			pinkLeavesID = config.getBlock("Pink Cherry Leaves ID", 314, null).getInt();
			blueLeavesID = config.getBlock("Magic Leaves ID", 315, null).getInt();
			whiteLeavesID = config.getBlock("White Cherry Leaves ID", 316, null).getInt();
			deadLeavesID = config.getBlock("Dying Leaves ID", 317, null).getInt();
			shortGrassID = config.getBlock("Short Grass ID", 318, null).getInt();
			appleLeavesID = config.getBlock("Apple Leaves ID", 319, null).getInt();
			sproutID = config.getBlock("Sprout ID", 320, null).getInt();
			bushID = config.getBlock("Bush ID", 321, null).getInt();
			bambooID = config.getBlock("Bamboo ID", 322, null).getInt();
			bambooLeavesID = config.getBlock("Bamboo Leaves ID", 323, null).getInt();
			deadGrassID = config.getBlock("Dead Grass ID", 324, null).getInt();
			desertGrassID = config.getBlock("Desert Grass ID", 325, null).getInt();
			whiteFlowerID = config.getBlock("Anenome ID", 326, null).getInt();
			blueFlowerID = config.getBlock("Swampflower ID", 327, null).getInt();
			purpleFlowerID = config.getBlock("Wildflower ID", 328, null).getInt();
			orangeFlowerID = config.getBlock("Daisy ID", 329, null).getInt();
			tinyFlowerID = config.getBlock("Clover ID", 330, null).getInt();
			glowFlowerID = config.getBlock("Glowflower ID", 331, null).getInt();
			cattailID = config.getBlock("Cattail ID", 332, null).getInt();
			willowID = config.getBlock("Willow ID", 333, null).getInt();
			autumnLeavesID = config.getBlock("Yellow Autumn Leaves ID", 334, null).getInt();
			thornID = config.getBlock("Thorns ID", 335, null).getInt();
			toadstoolID = config.getBlock("Toadstool ID", 336, null).getInt();
			highGrassBottomID = config.getBlock("High Grass Bottom ID", 337, null).getInt();
			highGrassTopID = config.getBlock("High Grass Top ID", 338, null).getInt();
			tinyCactusID = config.getBlock("Tiny Cactus ID", 339, null).getInt();
			firSaplingID = config.getBlock("Fir Sapling ID", 340, null).getInt();
			redwoodSaplingID = config.getBlock("Redwood Sapling ID", 341, null).getInt();
			palmSaplingID = config.getBlock("Palm Sapling ID", 342, null).getInt();
			redSaplingID = config.getBlock("Maple Sapling ID", 343, null).getInt();
			orangeSaplingID = config.getBlock("Orange Autumn Sapling ID", 344, null).getInt();
			yellowSaplingID = config.getBlock("Yellow Autumn Sapling ID", 345, null).getInt();
			brownSaplingID = config.getBlock("Dying Sapling ID", 346, null).getInt();
			willowSaplingID = config.getBlock("Willow Sapling ID", 347, null).getInt();
			appleSaplingID = config.getBlock("Apple Sapling ID", 348, null).getInt();
			originSaplingID = config.getBlock("Origin Sapling ID", 349, null).getInt();
			pinkSaplingID = config.getBlock("Pink Cherry Sapling ID", 350, null).getInt();
			whiteSaplingID = config.getBlock("White Cherry Sapling ID", 351, null).getInt();
			darkSaplingID = config.getBlock("Dark Sapling ID", 352, null).getInt();
			magicSaplingID = config.getBlock("Magic Sapling ID", 353, null).getInt();
			deathbloomID = config.getBlock("Deathbloom ID", 354, null).getInt();
			redRockCobbleID = config.getBlock("Red Rock Cobblestone ID", 355, null).getInt();
			redRockBrickID = config.getBlock("Red Rock Bricks ID", 356, null).getInt();
			hydrangeaID = config.getBlock("Hydrangea ID", 357, null).getInt();
			violetID = config.getBlock("Violet ID", 358, null).getInt();
			mediumGrassID = config.getBlock("Medium Grass ID", 359, null).getInt();
			duneGrassID = config.getBlock("Dune Grass ID", 360, null).getInt();
			desertSproutsID = config.getBlock("Desert Sprouts ID", 361, null).getInt();
			redRockCobbleDoubleSlabID = config.getBlock("Red Rock Cobblestone Double Slab ID", 362, null).getInt();
			redRockCobbleSingleSlabID = config.getBlock("Red Rock Cobblestone Single Slab ID", 363, null).getInt();
			redRockCobbleStairsID = config.getBlock("Red Rock Cobblestone Stairs ID", 364, null).getInt();
			redRockBrickDoubleSlabID = config.getBlock("Red Rock Brick Double Slab ID", 365, null).getInt();
			redRockBrickSingleSlabID = config.getBlock("Red Rock Brick Single Slab ID", 366, null).getInt();
			redRockBrickStairsID = config.getBlock("Red Rock Brick Stairs ID", 367, null).getInt();
			mudBrickDoubleSlabID = config.getBlock("Mud Brick Double Slab ID", 368, null).getInt();
			mudBrickSingleSlabID = config.getBlock("Mud Brick Single Slab ID", 369, null).getInt();
			mudBrickStairsID = config.getBlock("Mud Brick Stairs ID", 370, null).getInt();
			mangroveWoodID = config.getBlock("Mangrove Log ID", 371, null).getInt();
			mangroveLeavesID = config.getBlock("Mangrove Leaves ID", 372, null).getInt();
			mangroveSaplingID = config.getBlock("Mangrove Sapling ID", 373, null).getInt();
			mangrovePlankID = config.getBlock("Mangrove Plank ID", 374, null).getInt();
			mangroveDoubleSlabID = config.getBlock("Mangrove Double Slab ID", 375, null).getInt();
			mangroveSingleSlabID = config.getBlock("Mangrove Single Slab ID", 376, null).getInt();
			mangroveStairsID = config.getBlock("Mangrove Stairs ID", 377, null).getInt();
			acaciaSaplingID = config.getBlock("Acacia Sapling ID", 378, null).getInt();
			holyTallGrassID = config.getBlock("Holy Tall Grass ID", 379, null).getInt();
			promisedLandPortalID = config.getBlock("Promised Land Portal ID", 380, null).getInt();
			holyWoodID = config.getBlock("Holy Log ID", 381, null).getInt();
			holyLeavesID = config.getBlock("Holy Leaves ID", 382, null).getInt();
			holySaplingID = config.getBlock("Holy Sapling ID", 383, null).getInt();
			holyPlankID = config.getBlock("Holy Plank ID", 384, null).getInt();
			holyDoubleSlabID = config.getBlock("Holy Double Slab ID", 385, null).getInt();
			holySingleSlabID = config.getBlock("Holy Single Slab ID", 386, null).getInt();
			holyStairsID = config.getBlock("Holy Stairs ID", 387, null).getInt();
			amethystOreID = config.getBlock("Amethyst Ore ID", 388, null).getInt();
			amethystBlockID = config.getBlock("Block of Amethyst ID", 389, null).getInt();
			bambooThatchingID = config.getBlock("Bamboo Thatching ID", 390, null).getInt();
			mossID = config.getBlock("Moss ID", 391, null).getInt();
			algaeID = config.getBlock("Algae ID", 392, null).getInt();
			smolderingGrassID = config.getBlock("Smoldering Grass ID", 393, null).getInt();
			quicksandID = config.getBlock("Quicksand ID", 394, null).getInt();
			bambooSaplingID = config.getBlock("Bamboo Sapling ID", 395, null).getInt();

			// Get Item ID's
			shroomPowderID = config.getItem("Shroom Powder ID", 1001, null).getInt();
			mudBallID = config.getItem("Mud Ball ID", 1002, null).getInt();
			mudBrickID = config.getItem("Mud Brick ID", 1003, null).getInt();
			bambooItemID = config.getItem("Bamboo ID", 1004).getInt();
			cattailItemID = config.getItem("Cattail ID", 1005).getInt();
			ancientStaffID = config.getItem("Ancient Staff ID", 1006).getInt();
			enderporterID = config.getItem("Enderporter ID", 1007).getInt();
			ashesID = config.getItem("Pile of Ashes ID", 1008, null).getInt();
			barleyItemID = config.getItem("Barley ID", 1009).getInt();
			amethystID = config.getItem("Amethyst ID", 1010).getInt();
			ancientStaffHandleID = config.getItem("Ancient Staff Handle ID", 1011, null).getInt();
			ancientStaffPoleID = config.getItem("Ancient Staff Pole ID", 1012, null).getInt();
			ancientStaffTopperID = config.getItem("Ancient Staff Topper ID", 1013, null).getInt();
			shortGrassItemID = config.getItem("Short Grass (Item) ID", 1014, null).getInt();
			mediumGrassItemID = config.getItem("Medium Grass (Item) ID", 1015, null).getInt();
			bushItemID = config.getItem("Bush (Item) ID", 1016, null).getInt();
			sproutItemID = config.getItem("Sprout (Item) ID", 1017, null).getInt();
			mossItemID = config.getItem("Moss (Item) ID", 1018, null).getInt();
			bopDiscID = config.getItem("Traversia Music Disc ID", 1019, null).getInt();
			bopDiscMudID = config.getItem("Muddy Music Disc ID", 1020, null).getInt();
			swordMudID = config.getItem("Muddy Sword ID", 1060, null).getInt();
			shovelMudID = config.getItem("Muddy Shovel ID", 1061, null).getInt();
			pickaxeMudID = config.getItem("Muddy Pickaxe ID", 1062, null).getInt();
			axeMudID = config.getItem("Muddy Axe ID", 1063, null).getInt();
			hoeMudID = config.getItem("Muddy Hoe ID", 1064, null).getInt();
			helmetMudID = config.getItem("Muddy Helmet ID", 1065, null).getInt();
			chestplateMudID = config.getItem("Muddy Chestplate ID", 1066, null).getInt();
			leggingsMudID = config.getItem("Muddy Leggings ID", 1067, null).getInt();
			bootsMudID = config.getItem("Muddy Boots ID", 1068, null).getInt();
			swordAmethystID = config.getItem("Amethyst Sword ID", 1069, null).getInt();
			shovelAmethystID = config.getItem("Amethyst Shovel ID", 1070, null).getInt();
			pickaxeAmethystID = config.getItem("Amethyst Pickaxe ID", 1071, null).getInt();
			axeAmethystID = config.getItem("Amethyst Axe ID", 1072, null).getInt();
			hoeAmethystID = config.getItem("Amethyst Hoe ID", 1073, null).getInt();
			helmetAmethystID = config.getItem("Amethyst Helmet ID", 1074, null).getInt();
			chestplateAmethystID = config.getItem("Amethyst Chestplate ID", 1075, null).getInt();
			leggingsAmethystID = config.getItem("Amethyst Leggings ID", 1076, null).getInt();
			bootsAmethystID = config.getItem("Amethyst Boots ID", 1077, null).getInt();

			//Mob IDs
			jungleSpiderID = config.get("Mob IDs", "Jungle Spider ID", 101, null).getInt();
			rosesterID = config.get("Mob IDs", "Rosester ID", 102, null).getInt();

			System.out.println("Generating Biome ID's");
			alpsID = config.get("Biome IDs", "Alps ID", 171).getInt();
			arcticID = config.get("Biome IDs", "Arctic ID", 172).getInt();
			badlandsID = config.get("Biome IDs", "Badlands ID", 173).getInt();
			bambooForestID = config.get("Biome IDs", "Bamboo Forest ID", 174).getInt();
			bayouID = config.get("Biome IDs", "Bayou ID", 175).getInt();
			birchForestID = config.get("Biome IDs", "Birch Forest ID", 176).getInt();
			bogID = config.get("Biome IDs", "Bog ID", 177).getInt();
			borealForestID = config.get("Biome IDs", "Boreal Forest ID", 178).getInt();
			canyonID = config.get("Biome IDs", "Canyon ID", 179).getInt();
			chaparralID = config.get("Biome IDs", "Chaparral ID", 180).getInt();
			cherryBlossomGroveID = config.get("Biome IDs", "Cherry Blossom Grove ID", 181).getInt();
			coniferousForestID = config.get("Biome IDs", "Coniferous Forest ID", 182).getInt();
			cragID = config.get("Biome IDs", "Crag ID", 183).getInt();
			deadForestID = config.get("Biome IDs", "Dead Forest ID", 184).getInt();
			deadSwampID = config.get("Biome IDs", "Dead Swamp ID", 185).getInt();
			deadlandsID = config.get("Biome IDs", "Deadlands ID", 186).getInt();
			deciduousForestID = config.get("Biome IDs", "Deciduous Forest ID", 187).getInt();
			drylandsID = config.get("Biome IDs", "Drylands ID", 189).getInt();
			dunesID = config.get("Biome IDs", "Dunes ID", 190).getInt();
			fenID = config.get("Biome IDs", "Fen ID", 191).getInt();
			fieldID = config.get("Biome IDs", "Field ID", 192).getInt();
			frostForestID = config.get("Biome IDs", "Frost Forest ID", 193).getInt();
			fungiForestID = config.get("Biome IDs", "Fungi Forest ID", 194).getInt();
			gardenID = config.get("Biome IDs", "Garden ID", 195).getInt();
			glacierID = config.get("Biome IDs", "Glacier ID", 196).getInt();
			grasslandID = config.get("Biome IDs", "Grassland ID", 197).getInt();
			groveID = config.get("Biome IDs", "Grove ID", 198).getInt();
			heathlandID = config.get("Biome IDs", "Heathland ID", 199).getInt();
			highlandID = config.get("Biome IDs", "Highland ID", 200).getInt();
			iceSheetID = config.get("Biome IDs", "Ice Sheet ID", 201).getInt();
			icyHillsID = config.get("Biome IDs", "Icy Hills ID", 202).getInt();
			jadeCliffsID = config.get("Biome IDs", "Jade Cliffs ID", 203).getInt();
			lushDesertID = config.get("Biome IDs", "Lush Desert ID", 204).getInt();
			lushSwampID = config.get("Biome IDs", "Lush Swamp ID", 205).getInt();
			mangroveID = config.get("Biome IDs", "Mangrove ID", 206).getInt();
			
			//207-210 left for Mo Creatures
			
			mapleWoodsID = config.get("Biome IDs", "Maple Woods ID", 211).getInt();
			marshID = config.get("Biome IDs", "Marsh ID", 212).getInt();
			meadowID = config.get("Biome IDs", "Meadow ID", 213).getInt();
			mesaID = config.get("Biome IDs", "Mesa ID", 214).getInt();
			moorID = config.get("Biome IDs", "Moor ID", 215).getInt();
			mountainID = config.get("Biome IDs", "Mountain ID", 216).getInt();
			mysticGroveID = config.get("Biome IDs", "Mystic Grove ID", 217).getInt();
			oasisID = config.get("Biome IDs", "Oasis ID", 218).getInt();
			ominousWoodsID = config.get("Biome IDs", "Ominous Woods ID", 219).getInt();
			orchardID = config.get("Biome IDs", "Orchard ID", 220).getInt();
			originValleyID = config.get("Biome IDs", "Origin Valley ID", 221).getInt();
			outbackID = config.get("Biome IDs", "Outback ID", 222).getInt();
			pastureID = config.get("Biome IDs", "Pasture ID", 223).getInt();
			prairieID = config.get("Biome IDs", "Prairie ID", 224).getInt();
			promisedLandID = config.get("Biome IDs", "Promised Land ID", 225).getInt();
			quagmireID = config.get("Biome IDs", "Quagmire ID", 226).getInt();
			rainforestID = config.get("Biome IDs", "Rainforest ID", 227).getInt();
			redwoodForestID = config.get("Biome IDs", "Redwood Forest ID", 228).getInt();
			sacredSpringsID = config.get("Biome IDs", "Sacred Springs ID", 229).getInt();
			savannaID = config.get("Biome IDs", "Savanna ID", 230).getInt();
			scrublandID = config.get("Biome IDs", "Scrubland ID", 231).getInt();
			seasonalForestID = config.get("Biome IDs", "Seasonal Forest ID", 232).getInt();
			shieldID = config.get("Biome IDs", "Shield ID", 233).getInt();
			shoreID = config.get("Biome IDs", "Shore ID", 234).getInt();
			shrublandID = config.get("Biome IDs", "Shrubland ID", 235).getInt();
			snowyWoodsID = config.get("Biome IDs", "Snowy Woods ID", 236).getInt();
			spruceWoodsID = config.get("Biome IDs", "Spruce Woods ID", 237).getInt();
			steppeID = config.get("Biome IDs", "Steppe ID", 238).getInt();
			swampwoodsID = config.get("Biome IDs", "Swampwoods ID", 239).getInt();
			temperateRainforestID = config.get("Biome IDs", "Temperate Rainforest ID", 240).getInt();
			thicketID = config.get("Biome IDs", "Thicket ID", 241).getInt();
			tropicalRainforestID = config.get("Biome IDs", "Tropical Rainforest ID", 242).getInt();
			tropicsID = config.get("Biome IDs", "Tropics ID", 243).getInt();
			tundraID = config.get("Biome IDs", "Tundra ID", 244).getInt();
			volcanoID = config.get("Biome IDs", "Volcano ID", 245).getInt();
			wastelandID = config.get("Biome IDs", "Wasteland ID", 246).getInt();
			wetlandID = config.get("Biome IDs", "Wetland ID", 247).getInt();
			woodlandID = config.get("Biome IDs", "Woodland ID", 248).getInt();

			plainsNewID = config.get("Biome IDs", "Plains (New) ID", 249).getInt();
			desertNewID = config.get("Biome IDs", "Desert (New) ID", 250).getInt();
			forestNewID = config.get("Biome IDs", "Forest (New) ID", 251).getInt();
			taigaNewID = config.get("Biome IDs", "Taiga (New) ID", 252).getInt();
			swamplandNewID = config.get("Biome IDs", "Swampland (New) ID", 253).getInt();
			extremeHillsNewID = config.get("Biome IDs", "Extreme Hills (New) ID", 254).getInt();
			jungleNewID = config.get("Biome IDs", "Jungle (New) ID", 255).getInt();

			System.out.println("[BiomesOPlenty] Generated Config!");
		}
		catch (Exception e) 
		{
			FMLLog.log(Level.SEVERE, e, "Biomes O Plenty has had a problem loading its configuration");
		}
		finally 
		{
			config.save();
		}
	}
}
