/*******************************************************************************
 * Copyright 2022, the Glitchfiend Team.
 * All rights reserved.
 ******************************************************************************/
package biomesoplenty.init;

import biomesoplenty.api.block.BOPBlocks;
import biomesoplenty.api.block.BOPFluids;
import biomesoplenty.core.BiomesOPlenty;
import biomesoplenty.entity.BoatBOP;
import biomesoplenty.item.BoatItemBOP;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.*;

import java.util.function.BiConsumer;

import static biomesoplenty.api.item.BOPItems.*;

public class ModItems
{
    public static void setup(BiConsumer<ResourceLocation, Item> func)
    {
        registerItems(func);
        ModVanillaCompat.setup();
    }

    private static void registerItems(BiConsumer<ResourceLocation, Item> func)
    {
        registerBlockItems(func);

        BOP_ICON = register(func, new Item(new Item.Properties()), "bop_icon");

        ROSE_QUARTZ_CHUNK = register(func, new Item(new Item.Properties()), "rose_quartz_chunk");
        MUSIC_DISC_WANDERER = register(func, new Item((new Item.Properties()).stacksTo(1).rarity(Rarity.RARE).jukeboxPlayable(ModJukeboxSongs.WANDERER)), "music_disc_wanderer");
        BLOOD_BUCKET = register(func, new BucketItem(BOPFluids.BLOOD, (new Item.Properties()).craftRemainder(Items.BUCKET).stacksTo(1)), "blood_bucket");
        LIQUID_NULL_BUCKET = register(func, new BucketItem(BOPFluids.LIQUID_NULL, (new Item.Properties()).craftRemainder(Items.BUCKET).stacksTo(1)), "liquid_null_bucket");

        FIR_SIGN = register(func, new SignItem((new Item.Properties()).stacksTo(16), BOPBlocks.FIR_SIGN, BOPBlocks.FIR_WALL_SIGN), "fir_sign");
        FIR_HANGING_SIGN = register(func, new HangingSignItem(BOPBlocks.FIR_HANGING_SIGN, BOPBlocks.FIR_WALL_HANGING_SIGN, (new Item.Properties()).stacksTo(16)), "fir_hanging_sign");
        PINE_SIGN = register(func, new SignItem((new Item.Properties()).stacksTo(16), BOPBlocks.PINE_SIGN, BOPBlocks.PINE_WALL_SIGN), "pine_sign");
        PINE_HANGING_SIGN = register(func, new HangingSignItem(BOPBlocks.PINE_HANGING_SIGN, BOPBlocks.PINE_WALL_HANGING_SIGN, (new Item.Properties()).stacksTo(16)), "pine_hanging_sign");
        MAPLE_SIGN = register(func, new SignItem((new Item.Properties()).stacksTo(16), BOPBlocks.MAPLE_SIGN, BOPBlocks.MAPLE_WALL_SIGN), "maple_sign");
        MAPLE_HANGING_SIGN = register(func, new HangingSignItem(BOPBlocks.MAPLE_HANGING_SIGN, BOPBlocks.MAPLE_WALL_HANGING_SIGN, (new Item.Properties()).stacksTo(16)), "maple_hanging_sign");
        REDWOOD_SIGN = register(func, new SignItem((new Item.Properties()).stacksTo(16), BOPBlocks.REDWOOD_SIGN, BOPBlocks.REDWOOD_WALL_SIGN), "redwood_sign");
        REDWOOD_HANGING_SIGN = register(func, new HangingSignItem(BOPBlocks.REDWOOD_HANGING_SIGN, BOPBlocks.REDWOOD_WALL_HANGING_SIGN, (new Item.Properties()).stacksTo(16)), "redwood_hanging_sign");
        MAHOGANY_SIGN = register(func, new SignItem((new Item.Properties()).stacksTo(16), BOPBlocks.MAHOGANY_SIGN, BOPBlocks.MAHOGANY_WALL_SIGN), "mahogany_sign");
        MAHOGANY_HANGING_SIGN = register(func, new HangingSignItem(BOPBlocks.MAHOGANY_HANGING_SIGN, BOPBlocks.MAHOGANY_WALL_HANGING_SIGN, (new Item.Properties()).stacksTo(16)), "mahogany_hanging_sign");
        JACARANDA_SIGN = register(func, new SignItem((new Item.Properties()).stacksTo(16), BOPBlocks.JACARANDA_SIGN, BOPBlocks.JACARANDA_WALL_SIGN), "jacaranda_sign");
        JACARANDA_HANGING_SIGN = register(func, new HangingSignItem(BOPBlocks.JACARANDA_HANGING_SIGN, BOPBlocks.JACARANDA_WALL_HANGING_SIGN, (new Item.Properties()).stacksTo(16)), "jacaranda_hanging_sign");
        PALM_SIGN = register(func, new SignItem((new Item.Properties()).stacksTo(16), BOPBlocks.PALM_SIGN, BOPBlocks.PALM_WALL_SIGN), "palm_sign");
        PALM_HANGING_SIGN = register(func, new HangingSignItem(BOPBlocks.PALM_HANGING_SIGN, BOPBlocks.PALM_WALL_HANGING_SIGN, (new Item.Properties()).stacksTo(16)), "palm_hanging_sign");
        WILLOW_SIGN = register(func, new SignItem((new Item.Properties()).stacksTo(16), BOPBlocks.WILLOW_SIGN, BOPBlocks.WILLOW_WALL_SIGN), "willow_sign");
        WILLOW_HANGING_SIGN = register(func, new HangingSignItem(BOPBlocks.WILLOW_HANGING_SIGN, BOPBlocks.WILLOW_WALL_HANGING_SIGN, (new Item.Properties()).stacksTo(16)), "willow_hanging_sign");
        DEAD_SIGN = register(func, new SignItem((new Item.Properties()).stacksTo(16), BOPBlocks.DEAD_SIGN, BOPBlocks.DEAD_WALL_SIGN), "dead_sign");
        DEAD_HANGING_SIGN = register(func, new HangingSignItem(BOPBlocks.DEAD_HANGING_SIGN, BOPBlocks.DEAD_WALL_HANGING_SIGN, (new Item.Properties()).stacksTo(16)), "dead_hanging_sign");
        MAGIC_SIGN = register(func, new SignItem((new Item.Properties()).stacksTo(16), BOPBlocks.MAGIC_SIGN, BOPBlocks.MAGIC_WALL_SIGN), "magic_sign");
        MAGIC_HANGING_SIGN = register(func, new HangingSignItem(BOPBlocks.MAGIC_HANGING_SIGN, BOPBlocks.MAGIC_WALL_HANGING_SIGN, (new Item.Properties()).stacksTo(16)), "magic_hanging_sign");
        UMBRAN_SIGN = register(func, new SignItem((new Item.Properties()).stacksTo(16), BOPBlocks.UMBRAN_SIGN, BOPBlocks.UMBRAN_WALL_SIGN), "umbran_sign");
        UMBRAN_HANGING_SIGN = register(func, new HangingSignItem(BOPBlocks.UMBRAN_HANGING_SIGN, BOPBlocks.UMBRAN_WALL_HANGING_SIGN, (new Item.Properties()).stacksTo(16)), "umbran_hanging_sign");
        HELLBARK_SIGN = register(func, new SignItem((new Item.Properties()).stacksTo(16), BOPBlocks.HELLBARK_SIGN, BOPBlocks.HELLBARK_WALL_SIGN), "hellbark_sign");
        HELLBARK_HANGING_SIGN = register(func, new HangingSignItem(BOPBlocks.HELLBARK_HANGING_SIGN, BOPBlocks.HELLBARK_WALL_HANGING_SIGN, (new Item.Properties()).stacksTo(16)), "hellbark_hanging_sign");
        EMPYREAL_SIGN = register(func, new SignItem((new Item.Properties()).stacksTo(16), BOPBlocks.EMPYREAL_SIGN, BOPBlocks.EMPYREAL_WALL_SIGN), "empyreal_sign");
        EMPYREAL_HANGING_SIGN = register(func, new HangingSignItem(BOPBlocks.EMPYREAL_HANGING_SIGN, BOPBlocks.EMPYREAL_WALL_HANGING_SIGN, (new Item.Properties()).stacksTo(16)), "empyreal_hanging_sign");

        FIR_BOAT = register(func, new BoatItemBOP(false, BoatBOP.ModelType.FIR, (new Item.Properties()).stacksTo(1)), "fir_boat");
        FIR_CHEST_BOAT = register(func, new BoatItemBOP(true, BoatBOP.ModelType.FIR, (new Item.Properties()).stacksTo(1)), "fir_chest_boat");
        PINE_BOAT = register(func, new BoatItemBOP(false, BoatBOP.ModelType.PINE, (new Item.Properties()).stacksTo(1)), "pine_boat");
        PINE_CHEST_BOAT = register(func, new BoatItemBOP(true, BoatBOP.ModelType.PINE, (new Item.Properties()).stacksTo(1)), "pine_chest_boat");
        MAPLE_BOAT = register(func, new BoatItemBOP(false, BoatBOP.ModelType.MAPLE, (new Item.Properties()).stacksTo(1)), "maple_boat");
        MAPLE_CHEST_BOAT = register(func, new BoatItemBOP(true, BoatBOP.ModelType.MAPLE, (new Item.Properties()).stacksTo(1)), "maple_chest_boat");
        REDWOOD_BOAT = register(func, new BoatItemBOP(false, BoatBOP.ModelType.REDWOOD, (new Item.Properties()).stacksTo(1)), "redwood_boat");
        REDWOOD_CHEST_BOAT = register(func, new BoatItemBOP(true, BoatBOP.ModelType.REDWOOD, (new Item.Properties()).stacksTo(1)), "redwood_chest_boat");
        MAHOGANY_BOAT = register(func, new BoatItemBOP(false, BoatBOP.ModelType.MAHOGANY, (new Item.Properties()).stacksTo(1)), "mahogany_boat");
        MAHOGANY_CHEST_BOAT = register(func, new BoatItemBOP(true, BoatBOP.ModelType.MAHOGANY, (new Item.Properties()).stacksTo(1)), "mahogany_chest_boat");
        JACARANDA_BOAT = register(func, new BoatItemBOP(false, BoatBOP.ModelType.JACARANDA, (new Item.Properties()).stacksTo(1)), "jacaranda_boat");
        JACARANDA_CHEST_BOAT = register(func, new BoatItemBOP(true, BoatBOP.ModelType.JACARANDA, (new Item.Properties()).stacksTo(1)), "jacaranda_chest_boat");
        PALM_BOAT = register(func, new BoatItemBOP(false, BoatBOP.ModelType.PALM, (new Item.Properties()).stacksTo(1)), "palm_boat");
        PALM_CHEST_BOAT = register(func, new BoatItemBOP(true, BoatBOP.ModelType.PALM, (new Item.Properties()).stacksTo(1)), "palm_chest_boat");
        WILLOW_BOAT = register(func, new BoatItemBOP(false, BoatBOP.ModelType.WILLOW, (new Item.Properties()).stacksTo(1)), "willow_boat");
        WILLOW_CHEST_BOAT = register(func, new BoatItemBOP(true, BoatBOP.ModelType.WILLOW, (new Item.Properties()).stacksTo(1)), "willow_chest_boat");
        DEAD_BOAT = register(func, new BoatItemBOP(false, BoatBOP.ModelType.DEAD, (new Item.Properties()).stacksTo(1)), "dead_boat");
        DEAD_CHEST_BOAT = register(func, new BoatItemBOP(true, BoatBOP.ModelType.DEAD, (new Item.Properties()).stacksTo(1)), "dead_chest_boat");
        MAGIC_BOAT = register(func, new BoatItemBOP(false, BoatBOP.ModelType.MAGIC, (new Item.Properties()).stacksTo(1)), "magic_boat");
        MAGIC_CHEST_BOAT = register(func, new BoatItemBOP(true, BoatBOP.ModelType.MAGIC, (new Item.Properties()).stacksTo(1)), "magic_chest_boat");
        UMBRAN_BOAT = register(func, new BoatItemBOP(false, BoatBOP.ModelType.UMBRAN, (new Item.Properties()).stacksTo(1)), "umbran_boat");
        UMBRAN_CHEST_BOAT = register(func, new BoatItemBOP(true, BoatBOP.ModelType.UMBRAN, (new Item.Properties()).stacksTo(1)), "umbran_chest_boat");
        HELLBARK_BOAT = register(func, new BoatItemBOP(false, BoatBOP.ModelType.HELLBARK, (new Item.Properties()).stacksTo(1)), "hellbark_boat");
        HELLBARK_CHEST_BOAT = register(func, new BoatItemBOP(true, BoatBOP.ModelType.HELLBARK, (new Item.Properties()).stacksTo(1)), "hellbark_chest_boat");
        EMPYREAL_BOAT = register(func, new BoatItemBOP(false, BoatBOP.ModelType.EMPYREAL, (new Item.Properties()).stacksTo(1)), "empyreal_boat");
        EMPYREAL_CHEST_BOAT = register(func, new BoatItemBOP(true, BoatBOP.ModelType.EMPYREAL, (new Item.Properties()).stacksTo(1)), "empyreal_chest_boat");
    }

    public static void registerBlockItems(BiConsumer<ResourceLocation, Item> func)
    {
        BLOOD = register(func, "blood", new BlockItem(BOPBlocks.BLOOD, new Item.Properties()));
        LIQUID_NULL = register(func, "liquid_null", new BlockItem(BOPBlocks.LIQUID_NULL, new Item.Properties()));
        WHITE_SAND = register(func, "white_sand", new BlockItem(BOPBlocks.WHITE_SAND, new Item.Properties()));
        WHITE_SANDSTONE = register(func, "white_sandstone", new BlockItem(BOPBlocks.WHITE_SANDSTONE, new Item.Properties()));
        WHITE_SANDSTONE_STAIRS = register(func, "white_sandstone_stairs", new BlockItem(BOPBlocks.WHITE_SANDSTONE_STAIRS, new Item.Properties()));
        WHITE_SANDSTONE_SLAB = register(func, "white_sandstone_slab", new BlockItem(BOPBlocks.WHITE_SANDSTONE_SLAB, new Item.Properties()));
        WHITE_SANDSTONE_WALL = register(func, "white_sandstone_wall", new BlockItem(BOPBlocks.WHITE_SANDSTONE_WALL, new Item.Properties()));
        SMOOTH_WHITE_SANDSTONE = register(func, "smooth_white_sandstone", new BlockItem(BOPBlocks.SMOOTH_WHITE_SANDSTONE, new Item.Properties()));
        SMOOTH_WHITE_SANDSTONE_STAIRS = register(func, "smooth_white_sandstone_stairs", new BlockItem(BOPBlocks.SMOOTH_WHITE_SANDSTONE_STAIRS, new Item.Properties()));
        SMOOTH_WHITE_SANDSTONE_SLAB = register(func, "smooth_white_sandstone_slab", new BlockItem(BOPBlocks.SMOOTH_WHITE_SANDSTONE_SLAB, new Item.Properties()));
        CUT_WHITE_SANDSTONE = register(func, "cut_white_sandstone", new BlockItem(BOPBlocks.CUT_WHITE_SANDSTONE, new Item.Properties()));
        CUT_WHITE_SANDSTONE_SLAB = register(func, "cut_white_sandstone_slab", new BlockItem(BOPBlocks.CUT_WHITE_SANDSTONE_SLAB, new Item.Properties()));
        CHISELED_WHITE_SANDSTONE = register(func, "chiseled_white_sandstone", new BlockItem(BOPBlocks.CHISELED_WHITE_SANDSTONE, new Item.Properties()));
        ORANGE_SAND = register(func, "orange_sand", new BlockItem(BOPBlocks.ORANGE_SAND, new Item.Properties()));
        ORANGE_SANDSTONE = register(func, "orange_sandstone", new BlockItem(BOPBlocks.ORANGE_SANDSTONE, new Item.Properties()));
        ORANGE_SANDSTONE_STAIRS = register(func, "orange_sandstone_stairs", new BlockItem(BOPBlocks.ORANGE_SANDSTONE_STAIRS, new Item.Properties()));
        ORANGE_SANDSTONE_SLAB = register(func, "orange_sandstone_slab", new BlockItem(BOPBlocks.ORANGE_SANDSTONE_SLAB, new Item.Properties()));
        ORANGE_SANDSTONE_WALL = register(func, "orange_sandstone_wall", new BlockItem(BOPBlocks.ORANGE_SANDSTONE_WALL, new Item.Properties()));
        SMOOTH_ORANGE_SANDSTONE = register(func, "smooth_orange_sandstone", new BlockItem(BOPBlocks.SMOOTH_ORANGE_SANDSTONE, new Item.Properties()));
        SMOOTH_ORANGE_SANDSTONE_STAIRS = register(func, "smooth_orange_sandstone_stairs", new BlockItem(BOPBlocks.SMOOTH_ORANGE_SANDSTONE_STAIRS, new Item.Properties()));
        SMOOTH_ORANGE_SANDSTONE_SLAB = register(func, "smooth_orange_sandstone_slab", new BlockItem(BOPBlocks.SMOOTH_ORANGE_SANDSTONE_SLAB, new Item.Properties()));
        CUT_ORANGE_SANDSTONE = register(func, "cut_orange_sandstone", new BlockItem(BOPBlocks.CUT_ORANGE_SANDSTONE, new Item.Properties()));
        CUT_ORANGE_SANDSTONE_SLAB = register(func, "cut_orange_sandstone_slab", new BlockItem(BOPBlocks.CUT_ORANGE_SANDSTONE_SLAB, new Item.Properties()));
        CHISELED_ORANGE_SANDSTONE = register(func, "chiseled_orange_sandstone", new BlockItem(BOPBlocks.CHISELED_ORANGE_SANDSTONE, new Item.Properties()));
        MOSSY_BLACK_SAND = register(func, "mossy_black_sand", new BlockItem(BOPBlocks.MOSSY_BLACK_SAND, new Item.Properties()));
        BLACK_SAND = register(func, "black_sand", new BlockItem(BOPBlocks.BLACK_SAND, new Item.Properties()));
        BLACK_SANDSTONE = register(func, "black_sandstone", new BlockItem(BOPBlocks.BLACK_SANDSTONE, new Item.Properties()));
        BLACK_SANDSTONE_STAIRS = register(func, "black_sandstone_stairs", new BlockItem(BOPBlocks.BLACK_SANDSTONE_STAIRS, new Item.Properties()));
        BLACK_SANDSTONE_SLAB = register(func, "black_sandstone_slab", new BlockItem(BOPBlocks.BLACK_SANDSTONE_SLAB, new Item.Properties()));
        BLACK_SANDSTONE_WALL = register(func, "black_sandstone_wall", new BlockItem(BOPBlocks.BLACK_SANDSTONE_WALL, new Item.Properties()));
        SMOOTH_BLACK_SANDSTONE = register(func, "smooth_black_sandstone", new BlockItem(BOPBlocks.SMOOTH_BLACK_SANDSTONE, new Item.Properties()));
        SMOOTH_BLACK_SANDSTONE_STAIRS = register(func, "smooth_black_sandstone_stairs", new BlockItem(BOPBlocks.SMOOTH_BLACK_SANDSTONE_STAIRS, new Item.Properties()));
        SMOOTH_BLACK_SANDSTONE_SLAB = register(func, "smooth_black_sandstone_slab", new BlockItem(BOPBlocks.SMOOTH_BLACK_SANDSTONE_SLAB, new Item.Properties()));
        CUT_BLACK_SANDSTONE = register(func, "cut_black_sandstone", new BlockItem(BOPBlocks.CUT_BLACK_SANDSTONE, new Item.Properties()));
        CUT_BLACK_SANDSTONE_SLAB = register(func, "cut_black_sandstone_slab", new BlockItem(BOPBlocks.CUT_BLACK_SANDSTONE_SLAB, new Item.Properties()));
        CHISELED_BLACK_SANDSTONE = register(func, "chiseled_black_sandstone", new BlockItem(BOPBlocks.CHISELED_BLACK_SANDSTONE, new Item.Properties()));
        THERMAL_CALCITE = register(func, "thermal_calcite", new BlockItem(BOPBlocks.THERMAL_CALCITE, new Item.Properties()));
        THERMAL_CALCITE_VENT = register(func, "thermal_calcite_vent", new BlockItem(BOPBlocks.THERMAL_CALCITE_VENT, new Item.Properties()));
        DRIED_SALT = register(func, "dried_salt", new BlockItem(BOPBlocks.DRIED_SALT, new Item.Properties()));
        FLESH = register(func, "flesh", new BlockItem(BOPBlocks.FLESH, new Item.Properties()));
        POROUS_FLESH = register(func, "porous_flesh", new BlockItem(BOPBlocks.POROUS_FLESH, new Item.Properties()));
        FLESH_TENDONS = register(func, "flesh_tendons", new BlockItem(BOPBlocks.FLESH_TENDONS, new Item.Properties()));
        FLESH_TENDONS_STRAND = register(func, "flesh_tendons_strand", new BlockItem(BOPBlocks.FLESH_TENDONS_STRAND, new Item.Properties()));
        EYEBULB = register(func, "eyebulb", new BlockItem(BOPBlocks.EYEBULB, new Item.Properties()));
        HAIR = register(func, "hair", new BlockItem(BOPBlocks.HAIR, new Item.Properties()));
        PUS_BUBBLE = register(func, "pus_bubble", new BlockItem(BOPBlocks.PUS_BUBBLE, new Item.Properties()));
        BRIMSTONE = register(func, "brimstone", new BlockItem(BOPBlocks.BRIMSTONE, new Item.Properties()));
        BRIMSTONE_BRICKS = register(func, "brimstone_bricks", new BlockItem(BOPBlocks.BRIMSTONE_BRICKS, new Item.Properties()));
        BRIMSTONE_BRICK_STAIRS = register(func, "brimstone_brick_stairs", new BlockItem(BOPBlocks.BRIMSTONE_BRICK_STAIRS, new Item.Properties()));
        BRIMSTONE_BRICK_SLAB = register(func, "brimstone_brick_slab", new BlockItem(BOPBlocks.BRIMSTONE_BRICK_SLAB, new Item.Properties()));
        BRIMSTONE_BRICK_WALL = register(func, "brimstone_brick_wall", new BlockItem(BOPBlocks.BRIMSTONE_BRICK_WALL, new Item.Properties()));
        CHISELED_BRIMSTONE_BRICKS = register(func, "chiseled_brimstone_bricks", new BlockItem(BOPBlocks.CHISELED_BRIMSTONE_BRICKS, new Item.Properties()));
        BRIMSTONE_FUMAROLE = register(func, "brimstone_fumarole", new BlockItem(BOPBlocks.BRIMSTONE_FUMAROLE, new Item.Properties()));
        BRIMSTONE_CLUSTER = register(func, "brimstone_cluster", new BlockItem(BOPBlocks.BRIMSTONE_CLUSTER, new Item.Properties()));
        BRIMSTONE_BUD = register(func, "brimstone_bud", new BlockItem(BOPBlocks.BRIMSTONE_BUD, new Item.Properties()));
        BLACKSTONE_SPINES = register(func, "blackstone_spines", new BlockItem(BOPBlocks.BLACKSTONE_SPINES, new Item.Properties()));
        BLACKSTONE_BULB = register(func, "blackstone_bulb", new BlockItem(BOPBlocks.BLACKSTONE_BULB, new Item.Properties()));
        ROSE_QUARTZ_BLOCK = register(func, "rose_quartz_block", new BlockItem(BOPBlocks.ROSE_QUARTZ_BLOCK, new Item.Properties()));
        ROSE_QUARTZ_CLUSTER = register(func, "rose_quartz_cluster", new BlockItem(BOPBlocks.ROSE_QUARTZ_CLUSTER, new Item.Properties()));
        LARGE_ROSE_QUARTZ_BUD = register(func, "large_rose_quartz_bud", new BlockItem(BOPBlocks.LARGE_ROSE_QUARTZ_BUD, new Item.Properties()));
        MEDIUM_ROSE_QUARTZ_BUD = register(func, "medium_rose_quartz_bud", new BlockItem(BOPBlocks.MEDIUM_ROSE_QUARTZ_BUD, new Item.Properties()));
        SMALL_ROSE_QUARTZ_BUD = register(func, "small_rose_quartz_bud", new BlockItem(BOPBlocks.SMALL_ROSE_QUARTZ_BUD, new Item.Properties()));
        BARNACLES = register(func, "barnacles", new BlockItem(BOPBlocks.BARNACLES, new Item.Properties()));
        WISPJELLY = register(func, "wispjelly", new BlockItem(BOPBlocks.WISPJELLY, new Item.Properties()));
        ALGAL_END_STONE = register(func, "algal_end_stone", new BlockItem(BOPBlocks.ALGAL_END_STONE, new Item.Properties()));
        UNMAPPED_END_STONE = register(func, "unmapped_end_stone", new BlockItem(BOPBlocks.UNMAPPED_END_STONE, new Item.Properties()));
        NULL_END_STONE = register(func, "null_end_stone", new BlockItem(BOPBlocks.NULL_END_STONE, new Item.Properties()));
        NULL_BLOCK = register(func, "null_block", new BlockItem(BOPBlocks.NULL_BLOCK, new Item.Properties()));
        NULL_LEAVES = register(func, "null_leaves", new BlockItem(BOPBlocks.NULL_LEAVES, new Item.Properties()));
        NULL_PLANT = register(func, "null_plant", new BlockItem(BOPBlocks.NULL_PLANT, new Item.Properties()));
        ANOMALY = register(func, "anomaly", new BlockItem(BOPBlocks.ANOMALY, new Item.Properties()));
        TOADSTOOL = register(func, "toadstool", new BlockItem(BOPBlocks.TOADSTOOL, new Item.Properties()));
        TOADSTOOL_BLOCK = register(func, "toadstool_block", new BlockItem(BOPBlocks.TOADSTOOL_BLOCK, new Item.Properties()));
        GLOWSHROOM = register(func, "glowshroom", new BlockItem(BOPBlocks.GLOWSHROOM, new Item.Properties()));
        GLOWSHROOM_BLOCK = register(func, "glowshroom_block", new BlockItem(BOPBlocks.GLOWSHROOM_BLOCK, new Item.Properties()));
        GLOWING_MOSS_BLOCK = register(func, "glowing_moss_block", new BlockItem(BOPBlocks.GLOWING_MOSS_BLOCK, new Item.Properties()));
        GLOWING_MOSS_CARPET = register(func, "glowing_moss_carpet", new BlockItem(BOPBlocks.GLOWING_MOSS_CARPET, new Item.Properties()));
        GLOWWORM_SILK = register(func, "glowworm_silk", new BlockItem(BOPBlocks.GLOWWORM_SILK, new Item.Properties()));
        GLOWWORM_SILK_STRAND = register(func, "glowworm_silk_strand", new BlockItem(BOPBlocks.GLOWWORM_SILK_STRAND, new Item.Properties()));
        SPIDER_EGG = register(func, "spider_egg", new BlockItem(BOPBlocks.SPIDER_EGG, new Item.Properties()));
        HANGING_COBWEB = register(func, "hanging_cobweb", new BlockItem(BOPBlocks.HANGING_COBWEB, new Item.Properties()));
        HANGING_COBWEB_STRAND = register(func, "hanging_cobweb_strand", new BlockItem(BOPBlocks.HANGING_COBWEB_STRAND, new Item.Properties()));
        STRINGY_COBWEB = register(func, "stringy_cobweb", new BlockItem(BOPBlocks.STRINGY_COBWEB, new Item.Properties()));
        WEBBING = register(func, "webbing", new BlockItem(BOPBlocks.WEBBING, new Item.Properties()));
        ORIGIN_GRASS_BLOCK = register(func, "origin_grass_block", new BlockItem(BOPBlocks.ORIGIN_GRASS_BLOCK, new Item.Properties()));
        ORIGIN_SAPLING = register(func, "origin_sapling", new BlockItem(BOPBlocks.ORIGIN_SAPLING, new Item.Properties()));
        ORIGIN_LEAVES = register(func, "origin_leaves", new BlockItem(BOPBlocks.ORIGIN_LEAVES, new Item.Properties()));
        FLOWERING_OAK_SAPLING = register(func, "flowering_oak_sapling", new BlockItem(BOPBlocks.FLOWERING_OAK_SAPLING, new Item.Properties()));
        FLOWERING_OAK_LEAVES = register(func, "flowering_oak_leaves", new BlockItem(BOPBlocks.FLOWERING_OAK_LEAVES, new Item.Properties()));
        CYPRESS_SAPLING = register(func, "cypress_sapling", new BlockItem(BOPBlocks.CYPRESS_SAPLING, new Item.Properties()));
        CYPRESS_LEAVES = register(func, "cypress_leaves", new BlockItem(BOPBlocks.CYPRESS_LEAVES, new Item.Properties()));
        SNOWBLOSSOM_SAPLING = register(func, "snowblossom_sapling", new BlockItem(BOPBlocks.SNOWBLOSSOM_SAPLING, new Item.Properties()));
        SNOWBLOSSOM_LEAVES = register(func, "snowblossom_leaves", new BlockItem(BOPBlocks.SNOWBLOSSOM_LEAVES, new Item.Properties()));
        RAINBOW_BIRCH_SAPLING = register(func, "rainbow_birch_sapling", new BlockItem(BOPBlocks.RAINBOW_BIRCH_SAPLING, new Item.Properties()));
        RAINBOW_BIRCH_LEAVES = register(func, "rainbow_birch_leaves", new BlockItem(BOPBlocks.RAINBOW_BIRCH_LEAVES, new Item.Properties()));
        FIR_SAPLING = register(func, "fir_sapling", new BlockItem(BOPBlocks.FIR_SAPLING, new Item.Properties()));
        FIR_LEAVES = register(func, "fir_leaves", new BlockItem(BOPBlocks.FIR_LEAVES, new Item.Properties()));
        FIR_LOG = register(func, "fir_log", new BlockItem(BOPBlocks.FIR_LOG, new Item.Properties()));
        FIR_WOOD = register(func, "fir_wood", new BlockItem(BOPBlocks.FIR_WOOD, new Item.Properties()));
        STRIPPED_FIR_LOG = register(func, "stripped_fir_log", new BlockItem(BOPBlocks.STRIPPED_FIR_LOG, new Item.Properties()));
        STRIPPED_FIR_WOOD = register(func, "stripped_fir_wood", new BlockItem(BOPBlocks.STRIPPED_FIR_WOOD, new Item.Properties()));
        FIR_PLANKS = register(func, "fir_planks", new BlockItem(BOPBlocks.FIR_PLANKS, new Item.Properties()));
        FIR_STAIRS = register(func, "fir_stairs", new BlockItem(BOPBlocks.FIR_STAIRS, new Item.Properties()));
        FIR_SLAB = register(func, "fir_slab", new BlockItem(BOPBlocks.FIR_SLAB, new Item.Properties()));
        FIR_FENCE = register(func, "fir_fence", new BlockItem(BOPBlocks.FIR_FENCE, new Item.Properties()));
        FIR_FENCE_GATE = register(func, "fir_fence_gate", new BlockItem(BOPBlocks.FIR_FENCE_GATE, new Item.Properties()));
        FIR_DOOR = register(func, "fir_door", new BlockItem(BOPBlocks.FIR_DOOR, new Item.Properties()));
        FIR_TRAPDOOR = register(func, "fir_trapdoor", new BlockItem(BOPBlocks.FIR_TRAPDOOR, new Item.Properties()));
        FIR_PRESSURE_PLATE = register(func, "fir_pressure_plate", new BlockItem(BOPBlocks.FIR_PRESSURE_PLATE, new Item.Properties()));
        FIR_BUTTON = register(func, "fir_button", new BlockItem(BOPBlocks.FIR_BUTTON, new Item.Properties()));
        PINE_SAPLING = register(func, "pine_sapling", new BlockItem(BOPBlocks.PINE_SAPLING, new Item.Properties()));
        PINE_LEAVES = register(func, "pine_leaves", new BlockItem(BOPBlocks.PINE_LEAVES, new Item.Properties()));
        PINE_LOG = register(func, "pine_log", new BlockItem(BOPBlocks.PINE_LOG, new Item.Properties()));
        PINE_WOOD = register(func, "pine_wood", new BlockItem(BOPBlocks.PINE_WOOD, new Item.Properties()));
        STRIPPED_PINE_LOG = register(func, "stripped_pine_log", new BlockItem(BOPBlocks.STRIPPED_PINE_LOG, new Item.Properties()));
        STRIPPED_PINE_WOOD = register(func, "stripped_pine_wood", new BlockItem(BOPBlocks.STRIPPED_PINE_WOOD, new Item.Properties()));
        PINE_PLANKS = register(func, "pine_planks", new BlockItem(BOPBlocks.PINE_PLANKS, new Item.Properties()));
        PINE_STAIRS = register(func, "pine_stairs", new BlockItem(BOPBlocks.PINE_STAIRS, new Item.Properties()));
        PINE_SLAB = register(func, "pine_slab", new BlockItem(BOPBlocks.PINE_SLAB, new Item.Properties()));
        PINE_FENCE = register(func, "pine_fence", new BlockItem(BOPBlocks.PINE_FENCE, new Item.Properties()));
        PINE_FENCE_GATE = register(func, "pine_fence_gate", new BlockItem(BOPBlocks.PINE_FENCE_GATE, new Item.Properties()));
        PINE_DOOR = register(func, "pine_door", new BlockItem(BOPBlocks.PINE_DOOR, new Item.Properties()));
        PINE_TRAPDOOR = register(func, "pine_trapdoor", new BlockItem(BOPBlocks.PINE_TRAPDOOR, new Item.Properties()));
        PINE_PRESSURE_PLATE = register(func, "pine_pressure_plate", new BlockItem(BOPBlocks.PINE_PRESSURE_PLATE, new Item.Properties()));
        PINE_BUTTON = register(func, "pine_button", new BlockItem(BOPBlocks.PINE_BUTTON, new Item.Properties()));
        RED_MAPLE_SAPLING = register(func, "red_maple_sapling", new BlockItem(BOPBlocks.RED_MAPLE_SAPLING, new Item.Properties()));
        RED_MAPLE_LEAF_PILE = register(func, "red_maple_leaf_pile", new BlockItem(BOPBlocks.RED_MAPLE_LEAF_PILE, new Item.Properties()));
        RED_MAPLE_LEAVES = register(func, "red_maple_leaves", new BlockItem(BOPBlocks.RED_MAPLE_LEAVES, new Item.Properties()));
        ORANGE_MAPLE_SAPLING = register(func, "orange_maple_sapling", new BlockItem(BOPBlocks.ORANGE_MAPLE_SAPLING, new Item.Properties()));
        ORANGE_MAPLE_LEAF_PILE = register(func, "orange_maple_leaf_pile", new BlockItem(BOPBlocks.ORANGE_MAPLE_LEAF_PILE, new Item.Properties()));
        ORANGE_MAPLE_LEAVES = register(func, "orange_maple_leaves", new BlockItem(BOPBlocks.ORANGE_MAPLE_LEAVES, new Item.Properties()));
        YELLOW_MAPLE_SAPLING = register(func, "yellow_maple_sapling", new BlockItem(BOPBlocks.YELLOW_MAPLE_SAPLING, new Item.Properties()));
        YELLOW_MAPLE_LEAF_PILE = register(func, "yellow_maple_leaf_pile", new BlockItem(BOPBlocks.YELLOW_MAPLE_LEAF_PILE, new Item.Properties()));
        YELLOW_MAPLE_LEAVES = register(func, "yellow_maple_leaves", new BlockItem(BOPBlocks.YELLOW_MAPLE_LEAVES, new Item.Properties()));
        MAPLE_LOG = register(func, "maple_log", new BlockItem(BOPBlocks.MAPLE_LOG, new Item.Properties()));
        MAPLE_WOOD = register(func, "maple_wood", new BlockItem(BOPBlocks.MAPLE_WOOD, new Item.Properties()));
        STRIPPED_MAPLE_LOG = register(func, "stripped_maple_log", new BlockItem(BOPBlocks.STRIPPED_MAPLE_LOG, new Item.Properties()));
        STRIPPED_MAPLE_WOOD = register(func, "stripped_maple_wood", new BlockItem(BOPBlocks.STRIPPED_MAPLE_WOOD, new Item.Properties()));
        MAPLE_PLANKS = register(func, "maple_planks", new BlockItem(BOPBlocks.MAPLE_PLANKS, new Item.Properties()));
        MAPLE_STAIRS = register(func, "maple_stairs", new BlockItem(BOPBlocks.MAPLE_STAIRS, new Item.Properties()));
        MAPLE_SLAB = register(func, "maple_slab", new BlockItem(BOPBlocks.MAPLE_SLAB, new Item.Properties()));
        MAPLE_FENCE = register(func, "maple_fence", new BlockItem(BOPBlocks.MAPLE_FENCE, new Item.Properties()));
        MAPLE_FENCE_GATE = register(func, "maple_fence_gate", new BlockItem(BOPBlocks.MAPLE_FENCE_GATE, new Item.Properties()));
        MAPLE_DOOR = register(func, "maple_door", new BlockItem(BOPBlocks.MAPLE_DOOR, new Item.Properties()));
        MAPLE_TRAPDOOR = register(func, "maple_trapdoor", new BlockItem(BOPBlocks.MAPLE_TRAPDOOR, new Item.Properties()));
        MAPLE_PRESSURE_PLATE = register(func, "maple_pressure_plate", new BlockItem(BOPBlocks.MAPLE_PRESSURE_PLATE, new Item.Properties()));
        MAPLE_BUTTON = register(func, "maple_button", new BlockItem(BOPBlocks.MAPLE_BUTTON, new Item.Properties()));
        REDWOOD_SAPLING = register(func, "redwood_sapling", new BlockItem(BOPBlocks.REDWOOD_SAPLING, new Item.Properties()));
        REDWOOD_LEAVES = register(func, "redwood_leaves", new BlockItem(BOPBlocks.REDWOOD_LEAVES, new Item.Properties()));
        REDWOOD_LOG = register(func, "redwood_log", new BlockItem(BOPBlocks.REDWOOD_LOG, new Item.Properties()));
        REDWOOD_WOOD = register(func, "redwood_wood", new BlockItem(BOPBlocks.REDWOOD_WOOD, new Item.Properties()));
        STRIPPED_REDWOOD_LOG = register(func, "stripped_redwood_log", new BlockItem(BOPBlocks.STRIPPED_REDWOOD_LOG, new Item.Properties()));
        STRIPPED_REDWOOD_WOOD = register(func, "stripped_redwood_wood", new BlockItem(BOPBlocks.STRIPPED_REDWOOD_WOOD, new Item.Properties()));
        REDWOOD_PLANKS = register(func, "redwood_planks", new BlockItem(BOPBlocks.REDWOOD_PLANKS, new Item.Properties()));
        REDWOOD_STAIRS = register(func, "redwood_stairs", new BlockItem(BOPBlocks.REDWOOD_STAIRS, new Item.Properties()));
        REDWOOD_SLAB = register(func, "redwood_slab", new BlockItem(BOPBlocks.REDWOOD_SLAB, new Item.Properties()));
        REDWOOD_FENCE = register(func, "redwood_fence", new BlockItem(BOPBlocks.REDWOOD_FENCE, new Item.Properties()));
        REDWOOD_FENCE_GATE = register(func, "redwood_fence_gate", new BlockItem(BOPBlocks.REDWOOD_FENCE_GATE, new Item.Properties()));
        REDWOOD_DOOR = register(func, "redwood_door", new BlockItem(BOPBlocks.REDWOOD_DOOR, new Item.Properties()));
        REDWOOD_TRAPDOOR = register(func, "redwood_trapdoor", new BlockItem(BOPBlocks.REDWOOD_TRAPDOOR, new Item.Properties()));
        REDWOOD_PRESSURE_PLATE = register(func, "redwood_pressure_plate", new BlockItem(BOPBlocks.REDWOOD_PRESSURE_PLATE, new Item.Properties()));
        REDWOOD_BUTTON = register(func, "redwood_button", new BlockItem(BOPBlocks.REDWOOD_BUTTON, new Item.Properties()));
        MAHOGANY_SAPLING = register(func, "mahogany_sapling", new BlockItem(BOPBlocks.MAHOGANY_SAPLING, new Item.Properties()));
        MAHOGANY_LEAVES = register(func, "mahogany_leaves", new BlockItem(BOPBlocks.MAHOGANY_LEAVES, new Item.Properties()));
        MAHOGANY_LOG = register(func, "mahogany_log", new BlockItem(BOPBlocks.MAHOGANY_LOG, new Item.Properties()));
        MAHOGANY_WOOD = register(func, "mahogany_wood", new BlockItem(BOPBlocks.MAHOGANY_WOOD, new Item.Properties()));
        STRIPPED_MAHOGANY_LOG = register(func, "stripped_mahogany_log", new BlockItem(BOPBlocks.STRIPPED_MAHOGANY_LOG, new Item.Properties()));
        STRIPPED_MAHOGANY_WOOD = register(func, "stripped_mahogany_wood", new BlockItem(BOPBlocks.STRIPPED_MAHOGANY_WOOD, new Item.Properties()));
        MAHOGANY_PLANKS = register(func, "mahogany_planks", new BlockItem(BOPBlocks.MAHOGANY_PLANKS, new Item.Properties()));
        MAHOGANY_STAIRS = register(func, "mahogany_stairs", new BlockItem(BOPBlocks.MAHOGANY_STAIRS, new Item.Properties()));
        MAHOGANY_SLAB = register(func, "mahogany_slab", new BlockItem(BOPBlocks.MAHOGANY_SLAB, new Item.Properties()));
        MAHOGANY_FENCE = register(func, "mahogany_fence", new BlockItem(BOPBlocks.MAHOGANY_FENCE, new Item.Properties()));
        MAHOGANY_FENCE_GATE = register(func, "mahogany_fence_gate", new BlockItem(BOPBlocks.MAHOGANY_FENCE_GATE, new Item.Properties()));
        MAHOGANY_DOOR = register(func, "mahogany_door", new BlockItem(BOPBlocks.MAHOGANY_DOOR, new Item.Properties()));
        MAHOGANY_TRAPDOOR = register(func, "mahogany_trapdoor", new BlockItem(BOPBlocks.MAHOGANY_TRAPDOOR, new Item.Properties()));
        MAHOGANY_PRESSURE_PLATE = register(func, "mahogany_pressure_plate", new BlockItem(BOPBlocks.MAHOGANY_PRESSURE_PLATE, new Item.Properties()));
        MAHOGANY_BUTTON = register(func, "mahogany_button", new BlockItem(BOPBlocks.MAHOGANY_BUTTON, new Item.Properties()));
        JACARANDA_SAPLING = register(func, "jacaranda_sapling", new BlockItem(BOPBlocks.JACARANDA_SAPLING, new Item.Properties()));
        JACARANDA_LEAVES = register(func, "jacaranda_leaves", new BlockItem(BOPBlocks.JACARANDA_LEAVES, new Item.Properties()));
        JACARANDA_LOG = register(func, "jacaranda_log", new BlockItem(BOPBlocks.JACARANDA_LOG, new Item.Properties()));
        JACARANDA_WOOD = register(func, "jacaranda_wood", new BlockItem(BOPBlocks.JACARANDA_WOOD, new Item.Properties()));
        STRIPPED_JACARANDA_LOG = register(func, "stripped_jacaranda_log", new BlockItem(BOPBlocks.STRIPPED_JACARANDA_LOG, new Item.Properties()));
        STRIPPED_JACARANDA_WOOD = register(func, "stripped_jacaranda_wood", new BlockItem(BOPBlocks.STRIPPED_JACARANDA_WOOD, new Item.Properties()));
        JACARANDA_PLANKS = register(func, "jacaranda_planks", new BlockItem(BOPBlocks.JACARANDA_PLANKS, new Item.Properties()));
        JACARANDA_STAIRS = register(func, "jacaranda_stairs", new BlockItem(BOPBlocks.JACARANDA_STAIRS, new Item.Properties()));
        JACARANDA_SLAB = register(func, "jacaranda_slab", new BlockItem(BOPBlocks.JACARANDA_SLAB, new Item.Properties()));
        JACARANDA_FENCE = register(func, "jacaranda_fence", new BlockItem(BOPBlocks.JACARANDA_FENCE, new Item.Properties()));
        JACARANDA_FENCE_GATE = register(func, "jacaranda_fence_gate", new BlockItem(BOPBlocks.JACARANDA_FENCE_GATE, new Item.Properties()));
        JACARANDA_DOOR = register(func, "jacaranda_door", new BlockItem(BOPBlocks.JACARANDA_DOOR, new Item.Properties()));
        JACARANDA_TRAPDOOR = register(func, "jacaranda_trapdoor", new BlockItem(BOPBlocks.JACARANDA_TRAPDOOR, new Item.Properties()));
        JACARANDA_PRESSURE_PLATE = register(func, "jacaranda_pressure_plate", new BlockItem(BOPBlocks.JACARANDA_PRESSURE_PLATE, new Item.Properties()));
        JACARANDA_BUTTON = register(func, "jacaranda_button", new BlockItem(BOPBlocks.JACARANDA_BUTTON, new Item.Properties()));
        PALM_SAPLING = register(func, "palm_sapling", new BlockItem(BOPBlocks.PALM_SAPLING, new Item.Properties()));
        PALM_LEAVES = register(func, "palm_leaves", new BlockItem(BOPBlocks.PALM_LEAVES, new Item.Properties()));
        PALM_LOG = register(func, "palm_log", new BlockItem(BOPBlocks.PALM_LOG, new Item.Properties()));
        PALM_WOOD = register(func, "palm_wood", new BlockItem(BOPBlocks.PALM_WOOD, new Item.Properties()));
        STRIPPED_PALM_LOG = register(func, "stripped_palm_log", new BlockItem(BOPBlocks.STRIPPED_PALM_LOG, new Item.Properties()));
        STRIPPED_PALM_WOOD = register(func, "stripped_palm_wood", new BlockItem(BOPBlocks.STRIPPED_PALM_WOOD, new Item.Properties()));
        PALM_PLANKS = register(func, "palm_planks", new BlockItem(BOPBlocks.PALM_PLANKS, new Item.Properties()));
        PALM_STAIRS = register(func, "palm_stairs", new BlockItem(BOPBlocks.PALM_STAIRS, new Item.Properties()));
        PALM_SLAB = register(func, "palm_slab", new BlockItem(BOPBlocks.PALM_SLAB, new Item.Properties()));
        PALM_FENCE = register(func, "palm_fence", new BlockItem(BOPBlocks.PALM_FENCE, new Item.Properties()));
        PALM_FENCE_GATE = register(func, "palm_fence_gate", new BlockItem(BOPBlocks.PALM_FENCE_GATE, new Item.Properties()));
        PALM_DOOR = register(func, "palm_door", new BlockItem(BOPBlocks.PALM_DOOR, new Item.Properties()));
        PALM_TRAPDOOR = register(func, "palm_trapdoor", new BlockItem(BOPBlocks.PALM_TRAPDOOR, new Item.Properties()));
        PALM_PRESSURE_PLATE = register(func, "palm_pressure_plate", new BlockItem(BOPBlocks.PALM_PRESSURE_PLATE, new Item.Properties()));
        PALM_BUTTON = register(func, "palm_button", new BlockItem(BOPBlocks.PALM_BUTTON, new Item.Properties()));
        WILLOW_SAPLING = register(func, "willow_sapling", new BlockItem(BOPBlocks.WILLOW_SAPLING, new Item.Properties()));
        WILLOW_VINE = register(func, "willow_vine", new BlockItem(BOPBlocks.WILLOW_VINE, new Item.Properties()));
        SPANISH_MOSS = register(func, "spanish_moss", new BlockItem(BOPBlocks.SPANISH_MOSS, new Item.Properties()));
        SPANISH_MOSS_PLANT = register(func, "spanish_moss_plant", new BlockItem(BOPBlocks.SPANISH_MOSS_PLANT, new Item.Properties()));
        WILLOW_LEAVES = register(func, "willow_leaves", new BlockItem(BOPBlocks.WILLOW_LEAVES, new Item.Properties()));
        WILLOW_LOG = register(func, "willow_log", new BlockItem(BOPBlocks.WILLOW_LOG, new Item.Properties()));
        WILLOW_WOOD = register(func, "willow_wood", new BlockItem(BOPBlocks.WILLOW_WOOD, new Item.Properties()));
        STRIPPED_WILLOW_LOG = register(func, "stripped_willow_log", new BlockItem(BOPBlocks.STRIPPED_WILLOW_LOG, new Item.Properties()));
        STRIPPED_WILLOW_WOOD = register(func, "stripped_willow_wood", new BlockItem(BOPBlocks.STRIPPED_WILLOW_WOOD, new Item.Properties()));
        WILLOW_PLANKS = register(func, "willow_planks", new BlockItem(BOPBlocks.WILLOW_PLANKS, new Item.Properties()));
        WILLOW_STAIRS = register(func, "willow_stairs", new BlockItem(BOPBlocks.WILLOW_STAIRS, new Item.Properties()));
        WILLOW_SLAB = register(func, "willow_slab", new BlockItem(BOPBlocks.WILLOW_SLAB, new Item.Properties()));
        WILLOW_FENCE = register(func, "willow_fence", new BlockItem(BOPBlocks.WILLOW_FENCE, new Item.Properties()));
        WILLOW_FENCE_GATE = register(func, "willow_fence_gate", new BlockItem(BOPBlocks.WILLOW_FENCE_GATE, new Item.Properties()));
        WILLOW_DOOR = register(func, "willow_door", new BlockItem(BOPBlocks.WILLOW_DOOR, new Item.Properties()));
        WILLOW_TRAPDOOR = register(func, "willow_trapdoor", new BlockItem(BOPBlocks.WILLOW_TRAPDOOR, new Item.Properties()));
        WILLOW_PRESSURE_PLATE = register(func, "willow_pressure_plate", new BlockItem(BOPBlocks.WILLOW_PRESSURE_PLATE, new Item.Properties()));
        WILLOW_BUTTON = register(func, "willow_button", new BlockItem(BOPBlocks.WILLOW_BUTTON, new Item.Properties()));
        DEAD_SAPLING = register(func, "dead_sapling", new BlockItem(BOPBlocks.DEAD_SAPLING, new Item.Properties()));
        DEAD_BRANCH = register(func, "dead_branch", new BlockItem(BOPBlocks.DEAD_BRANCH, new Item.Properties()));
        DEAD_LEAVES = register(func, "dead_leaves", new BlockItem(BOPBlocks.DEAD_LEAVES, new Item.Properties()));
        DEAD_LOG = register(func, "dead_log", new BlockItem(BOPBlocks.DEAD_LOG, new Item.Properties()));
        DEAD_WOOD = register(func, "dead_wood", new BlockItem(BOPBlocks.DEAD_WOOD, new Item.Properties()));
        STRIPPED_DEAD_LOG = register(func, "stripped_dead_log", new BlockItem(BOPBlocks.STRIPPED_DEAD_LOG, new Item.Properties()));
        STRIPPED_DEAD_WOOD = register(func, "stripped_dead_wood", new BlockItem(BOPBlocks.STRIPPED_DEAD_WOOD, new Item.Properties()));
        DEAD_PLANKS = register(func, "dead_planks", new BlockItem(BOPBlocks.DEAD_PLANKS, new Item.Properties()));
        DEAD_STAIRS = register(func, "dead_stairs", new BlockItem(BOPBlocks.DEAD_STAIRS, new Item.Properties()));
        DEAD_SLAB = register(func, "dead_slab", new BlockItem(BOPBlocks.DEAD_SLAB, new Item.Properties()));
        DEAD_FENCE = register(func, "dead_fence", new BlockItem(BOPBlocks.DEAD_FENCE, new Item.Properties()));
        DEAD_FENCE_GATE = register(func, "dead_fence_gate", new BlockItem(BOPBlocks.DEAD_FENCE_GATE, new Item.Properties()));
        DEAD_DOOR = register(func, "dead_door", new BlockItem(BOPBlocks.DEAD_DOOR, new Item.Properties()));
        DEAD_TRAPDOOR = register(func, "dead_trapdoor", new BlockItem(BOPBlocks.DEAD_TRAPDOOR, new Item.Properties()));
        DEAD_PRESSURE_PLATE = register(func, "dead_pressure_plate", new BlockItem(BOPBlocks.DEAD_PRESSURE_PLATE, new Item.Properties()));
        DEAD_BUTTON = register(func, "dead_button", new BlockItem(BOPBlocks.DEAD_BUTTON, new Item.Properties()));
        MAGIC_SAPLING = register(func, "magic_sapling", new BlockItem(BOPBlocks.MAGIC_SAPLING, new Item.Properties()));
        MAGIC_LEAVES = register(func, "magic_leaves", new BlockItem(BOPBlocks.MAGIC_LEAVES, new Item.Properties()));
        MAGIC_LOG = register(func, "magic_log", new BlockItem(BOPBlocks.MAGIC_LOG, new Item.Properties()));
        MAGIC_WOOD = register(func, "magic_wood", new BlockItem(BOPBlocks.MAGIC_WOOD, new Item.Properties()));
        STRIPPED_MAGIC_LOG = register(func, "stripped_magic_log", new BlockItem(BOPBlocks.STRIPPED_MAGIC_LOG, new Item.Properties()));
        STRIPPED_MAGIC_WOOD = register(func, "stripped_magic_wood", new BlockItem(BOPBlocks.STRIPPED_MAGIC_WOOD, new Item.Properties()));
        MAGIC_PLANKS = register(func, "magic_planks", new BlockItem(BOPBlocks.MAGIC_PLANKS, new Item.Properties()));
        MAGIC_STAIRS = register(func, "magic_stairs", new BlockItem(BOPBlocks.MAGIC_STAIRS, new Item.Properties()));
        MAGIC_SLAB = register(func, "magic_slab", new BlockItem(BOPBlocks.MAGIC_SLAB, new Item.Properties()));
        MAGIC_FENCE = register(func, "magic_fence", new BlockItem(BOPBlocks.MAGIC_FENCE, new Item.Properties()));
        MAGIC_FENCE_GATE = register(func, "magic_fence_gate", new BlockItem(BOPBlocks.MAGIC_FENCE_GATE, new Item.Properties()));
        MAGIC_DOOR = register(func, "magic_door", new BlockItem(BOPBlocks.MAGIC_DOOR, new Item.Properties()));
        MAGIC_TRAPDOOR = register(func, "magic_trapdoor", new BlockItem(BOPBlocks.MAGIC_TRAPDOOR, new Item.Properties()));
        MAGIC_PRESSURE_PLATE = register(func, "magic_pressure_plate", new BlockItem(BOPBlocks.MAGIC_PRESSURE_PLATE, new Item.Properties()));
        MAGIC_BUTTON = register(func, "magic_button", new BlockItem(BOPBlocks.MAGIC_BUTTON, new Item.Properties()));
        UMBRAN_SAPLING = register(func, "umbran_sapling", new BlockItem(BOPBlocks.UMBRAN_SAPLING, new Item.Properties()));
        UMBRAN_LEAVES = register(func, "umbran_leaves", new BlockItem(BOPBlocks.UMBRAN_LEAVES, new Item.Properties()));
        UMBRAN_LOG = register(func, "umbran_log", new BlockItem(BOPBlocks.UMBRAN_LOG, new Item.Properties()));
        UMBRAN_WOOD = register(func, "umbran_wood", new BlockItem(BOPBlocks.UMBRAN_WOOD, new Item.Properties()));
        STRIPPED_UMBRAN_LOG = register(func, "stripped_umbran_log", new BlockItem(BOPBlocks.STRIPPED_UMBRAN_LOG, new Item.Properties()));
        STRIPPED_UMBRAN_WOOD = register(func, "stripped_umbran_wood", new BlockItem(BOPBlocks.STRIPPED_UMBRAN_WOOD, new Item.Properties()));
        UMBRAN_PLANKS = register(func, "umbran_planks", new BlockItem(BOPBlocks.UMBRAN_PLANKS, new Item.Properties()));
        UMBRAN_STAIRS = register(func, "umbran_stairs", new BlockItem(BOPBlocks.UMBRAN_STAIRS, new Item.Properties()));
        UMBRAN_SLAB = register(func, "umbran_slab", new BlockItem(BOPBlocks.UMBRAN_SLAB, new Item.Properties()));
        UMBRAN_FENCE = register(func, "umbran_fence", new BlockItem(BOPBlocks.UMBRAN_FENCE, new Item.Properties()));
        UMBRAN_FENCE_GATE = register(func, "umbran_fence_gate", new BlockItem(BOPBlocks.UMBRAN_FENCE_GATE, new Item.Properties()));
        UMBRAN_DOOR = register(func, "umbran_door", new BlockItem(BOPBlocks.UMBRAN_DOOR, new Item.Properties()));
        UMBRAN_TRAPDOOR = register(func, "umbran_trapdoor", new BlockItem(BOPBlocks.UMBRAN_TRAPDOOR, new Item.Properties()));
        UMBRAN_PRESSURE_PLATE = register(func, "umbran_pressure_plate", new BlockItem(BOPBlocks.UMBRAN_PRESSURE_PLATE, new Item.Properties()));
        UMBRAN_BUTTON = register(func, "umbran_button", new BlockItem(BOPBlocks.UMBRAN_BUTTON, new Item.Properties()));
        HELLBARK_SAPLING = register(func, "hellbark_sapling", new BlockItem(BOPBlocks.HELLBARK_SAPLING, new Item.Properties()));
        HELLBARK_LEAVES = register(func, "hellbark_leaves", new BlockItem(BOPBlocks.HELLBARK_LEAVES, new Item.Properties()));
        HELLBARK_LOG = register(func, "hellbark_log", new BlockItem(BOPBlocks.HELLBARK_LOG, new Item.Properties()));
        HELLBARK_WOOD = register(func, "hellbark_wood", new BlockItem(BOPBlocks.HELLBARK_WOOD, new Item.Properties()));
        STRIPPED_HELLBARK_LOG = register(func, "stripped_hellbark_log", new BlockItem(BOPBlocks.STRIPPED_HELLBARK_LOG, new Item.Properties()));
        STRIPPED_HELLBARK_WOOD = register(func, "stripped_hellbark_wood", new BlockItem(BOPBlocks.STRIPPED_HELLBARK_WOOD, new Item.Properties()));
        HELLBARK_PLANKS = register(func, "hellbark_planks", new BlockItem(BOPBlocks.HELLBARK_PLANKS, new Item.Properties()));
        HELLBARK_STAIRS = register(func, "hellbark_stairs", new BlockItem(BOPBlocks.HELLBARK_STAIRS, new Item.Properties()));
        HELLBARK_SLAB = register(func, "hellbark_slab", new BlockItem(BOPBlocks.HELLBARK_SLAB, new Item.Properties()));
        HELLBARK_FENCE = register(func, "hellbark_fence", new BlockItem(BOPBlocks.HELLBARK_FENCE, new Item.Properties()));
        HELLBARK_FENCE_GATE = register(func, "hellbark_fence_gate", new BlockItem(BOPBlocks.HELLBARK_FENCE_GATE, new Item.Properties()));
        HELLBARK_DOOR = register(func, "hellbark_door", new BlockItem(BOPBlocks.HELLBARK_DOOR, new Item.Properties()));
        HELLBARK_TRAPDOOR = register(func, "hellbark_trapdoor", new BlockItem(BOPBlocks.HELLBARK_TRAPDOOR, new Item.Properties()));
        HELLBARK_PRESSURE_PLATE = register(func, "hellbark_pressure_plate", new BlockItem(BOPBlocks.HELLBARK_PRESSURE_PLATE, new Item.Properties()));
        HELLBARK_BUTTON = register(func, "hellbark_button", new BlockItem(BOPBlocks.HELLBARK_BUTTON, new Item.Properties()));
        EMPYREAL_SAPLING = register(func, "empyreal_sapling", new BlockItem(BOPBlocks.EMPYREAL_SAPLING, new Item.Properties()));
        EMPYREAL_LEAVES = register(func, "empyreal_leaves", new BlockItem(BOPBlocks.EMPYREAL_LEAVES, new Item.Properties()));
        EMPYREAL_LOG = register(func, "empyreal_log", new BlockItem(BOPBlocks.EMPYREAL_LOG, new Item.Properties()));
        EMPYREAL_WOOD = register(func, "empyreal_wood", new BlockItem(BOPBlocks.EMPYREAL_WOOD, new Item.Properties()));
        STRIPPED_EMPYREAL_LOG = register(func, "stripped_empyreal_log", new BlockItem(BOPBlocks.STRIPPED_EMPYREAL_LOG, new Item.Properties()));
        STRIPPED_EMPYREAL_WOOD = register(func, "stripped_empyreal_wood", new BlockItem(BOPBlocks.STRIPPED_EMPYREAL_WOOD, new Item.Properties()));
        EMPYREAL_PLANKS = register(func, "empyreal_planks", new BlockItem(BOPBlocks.EMPYREAL_PLANKS, new Item.Properties()));
        EMPYREAL_STAIRS = register(func, "empyreal_stairs", new BlockItem(BOPBlocks.EMPYREAL_STAIRS, new Item.Properties()));
        EMPYREAL_SLAB = register(func, "empyreal_slab", new BlockItem(BOPBlocks.EMPYREAL_SLAB, new Item.Properties()));
        EMPYREAL_FENCE = register(func, "empyreal_fence", new BlockItem(BOPBlocks.EMPYREAL_FENCE, new Item.Properties()));
        EMPYREAL_FENCE_GATE = register(func, "empyreal_fence_gate", new BlockItem(BOPBlocks.EMPYREAL_FENCE_GATE, new Item.Properties()));
        EMPYREAL_DOOR = register(func, "empyreal_door", new BlockItem(BOPBlocks.EMPYREAL_DOOR, new Item.Properties()));
        EMPYREAL_TRAPDOOR = register(func, "empyreal_trapdoor", new BlockItem(BOPBlocks.EMPYREAL_TRAPDOOR, new Item.Properties()));
        EMPYREAL_PRESSURE_PLATE = register(func, "empyreal_pressure_plate", new BlockItem(BOPBlocks.EMPYREAL_PRESSURE_PLATE, new Item.Properties()));
        EMPYREAL_BUTTON = register(func, "empyreal_button", new BlockItem(BOPBlocks.EMPYREAL_BUTTON, new Item.Properties()));
        ROSE = register(func, "rose", new BlockItem(BOPBlocks.ROSE, new Item.Properties()));
        VIOLET = register(func, "violet", new BlockItem(BOPBlocks.VIOLET, new Item.Properties()));
        LAVENDER = register(func, "lavender", new BlockItem(BOPBlocks.LAVENDER, new Item.Properties()));
        TALL_LAVENDER = register(func, "tall_lavender", new BlockItem(BOPBlocks.TALL_LAVENDER, new Item.Properties()));
        WHITE_LAVENDER = register(func, "white_lavender", new BlockItem(BOPBlocks.WHITE_LAVENDER, new Item.Properties()));
        TALL_WHITE_LAVENDER = register(func, "tall_white_lavender", new BlockItem(BOPBlocks.TALL_WHITE_LAVENDER, new Item.Properties()));
        BLUE_HYDRANGEA = register(func, "blue_hydrangea", new BlockItem(BOPBlocks.BLUE_HYDRANGEA, new Item.Properties()));
        WILDFLOWER = register(func, "wildflower", new BlockItem(BOPBlocks.WILDFLOWER, new Item.Properties()));
        GOLDENROD = register(func, "goldenrod", new BlockItem(BOPBlocks.GOLDENROD, new Item.Properties()));
        ORANGE_COSMOS = register(func, "orange_cosmos", new BlockItem(BOPBlocks.ORANGE_COSMOS, new Item.Properties()));
        PINK_DAFFODIL = register(func, "pink_daffodil", new BlockItem(BOPBlocks.PINK_DAFFODIL, new Item.Properties()));
        PINK_HIBISCUS = register(func, "pink_hibiscus", new BlockItem(BOPBlocks.PINK_HIBISCUS, new Item.Properties()));
        WHITE_PETALS = register(func, "white_petals", new BlockItem(BOPBlocks.WHITE_PETALS, new Item.Properties()));
        ICY_IRIS = register(func, "icy_iris", new BlockItem(BOPBlocks.ICY_IRIS, new Item.Properties()));
        GLOWFLOWER = register(func, "glowflower", new BlockItem(BOPBlocks.GLOWFLOWER, new Item.Properties()));
        WILTED_LILY = register(func, "wilted_lily", new BlockItem(BOPBlocks.WILTED_LILY, new Item.Properties()));
        BURNING_BLOSSOM = register(func, "burning_blossom", new BlockItem(BOPBlocks.BURNING_BLOSSOM, new Item.Properties()));
        ENDBLOOM = register(func, "endbloom", new BlockItem(BOPBlocks.ENDBLOOM, new Item.Properties()));
        SPROUT = register(func, "sprout", new BlockItem(BOPBlocks.SPROUT, new Item.Properties()));
        BUSH = register(func, "bush", new BlockItem(BOPBlocks.BUSH, new Item.Properties()));
        HIGH_GRASS = register(func, "high_grass", new BlockItem(BOPBlocks.HIGH_GRASS, new Item.Properties()));
        HIGH_GRASS_PLANT = register(func, "high_grass_plant", new BlockItem(BOPBlocks.HIGH_GRASS_PLANT, new Item.Properties()));
        CLOVER = register(func, "clover", new BlockItem(BOPBlocks.CLOVER, new Item.Properties()));
        HUGE_CLOVER_PETAL = register(func, "huge_clover_petal", new BlockItem(BOPBlocks.HUGE_CLOVER_PETAL, new Item.Properties()));
        HUGE_LILY_PAD = register(func, "huge_lily_pad", new PlaceOnWaterBlockItem(BOPBlocks.HUGE_LILY_PAD, new Item.Properties()));
        WATERLILY = register(func, "waterlily", new PlaceOnWaterBlockItem(BOPBlocks.WATERLILY, new Item.Properties()));
        DUNE_GRASS = register(func, "dune_grass", new BlockItem(BOPBlocks.DUNE_GRASS, new Item.Properties()));
        DESERT_GRASS = register(func, "desert_grass", new BlockItem(BOPBlocks.DESERT_GRASS, new Item.Properties()));
        DEAD_GRASS = register(func, "dead_grass", new BlockItem(BOPBlocks.DEAD_GRASS, new Item.Properties()));
        TUNDRA_SHRUB = register(func, "tundra_shrub", new BlockItem(BOPBlocks.TUNDRA_SHRUB, new Item.Properties()));
        ENDERPHYTE = register(func, "enderphyte", new BlockItem(BOPBlocks.ENDERPHYTE, new Item.Properties()));
        LUMALOOP = register(func, "lumaloop", new BlockItem(BOPBlocks.LUMALOOP, new Item.Properties()));
        LUMALOOP_PLANT = register(func, "lumaloop_plant", new BlockItem(BOPBlocks.LUMALOOP_PLANT, new Item.Properties()));
        BARLEY = register(func, "barley", new BlockItem(BOPBlocks.BARLEY, new Item.Properties()));
        SEA_OATS = register(func, "sea_oats", new BlockItem(BOPBlocks.SEA_OATS, new Item.Properties()));
        CATTAIL = register(func, "cattail", new BlockItem(BOPBlocks.CATTAIL, new Item.Properties()));
        REED = register(func, "reed", new BlockItem(BOPBlocks.REED, new Item.Properties()));
        WATERGRASS = register(func, "watergrass", new BlockItem(BOPBlocks.WATERGRASS, new Item.Properties()));
        TINY_CACTUS = register(func, "tiny_cactus", new BlockItem(BOPBlocks.TINY_CACTUS, new Item.Properties()));
        BRAMBLE = register(func, "bramble", new BlockItem(BOPBlocks.BRAMBLE, new Item.Properties()));
        BRAMBLE_LEAVES = register(func, "bramble_leaves", new BlockItem(BOPBlocks.BRAMBLE_LEAVES, new Item.Properties()));
        POTTED_ORIGIN_SAPLING = register(func, "potted_origin_sapling", new BlockItem(BOPBlocks.POTTED_ORIGIN_SAPLING, new Item.Properties()));
        POTTED_FLOWERING_OAK_SAPLING = register(func, "potted_flowering_oak_sapling", new BlockItem(BOPBlocks.POTTED_FLOWERING_OAK_SAPLING, new Item.Properties()));
        POTTED_CYPRESS_SAPLING = register(func, "potted_cypress_sapling", new BlockItem(BOPBlocks.POTTED_CYPRESS_SAPLING, new Item.Properties()));
        POTTED_SNOWBLOSSOM_SAPLING = register(func, "potted_snowblossom_sapling", new BlockItem(BOPBlocks.POTTED_SNOWBLOSSOM_SAPLING, new Item.Properties()));
        POTTED_RAINBOW_BIRCH_SAPLING = register(func, "potted_rainbow_birch_sapling", new BlockItem(BOPBlocks.POTTED_RAINBOW_BIRCH_SAPLING, new Item.Properties()));
        POTTED_FIR_SAPLING = register(func, "potted_fir_sapling", new BlockItem(BOPBlocks.POTTED_FIR_SAPLING, new Item.Properties()));
        POTTED_PINE_SAPLING = register(func, "potted_pine_sapling", new BlockItem(BOPBlocks.POTTED_PINE_SAPLING, new Item.Properties()));
        POTTED_RED_MAPLE_SAPLING = register(func, "potted_red_maple_sapling", new BlockItem(BOPBlocks.POTTED_RED_MAPLE_SAPLING, new Item.Properties()));
        POTTED_ORANGE_MAPLE_SAPLING = register(func, "potted_orange_maple_sapling", new BlockItem(BOPBlocks.POTTED_ORANGE_MAPLE_SAPLING, new Item.Properties()));
        POTTED_YELLOW_MAPLE_SAPLING = register(func, "potted_yellow_maple_sapling", new BlockItem(BOPBlocks.POTTED_YELLOW_MAPLE_SAPLING, new Item.Properties()));
        POTTED_REDWOOD_SAPLING = register(func, "potted_redwood_sapling", new BlockItem(BOPBlocks.POTTED_REDWOOD_SAPLING, new Item.Properties()));
        POTTED_MAHOGANY_SAPLING = register(func, "potted_mahogany_sapling", new BlockItem(BOPBlocks.POTTED_MAHOGANY_SAPLING, new Item.Properties()));
        POTTED_JACARANDA_SAPLING = register(func, "potted_jacaranda_sapling", new BlockItem(BOPBlocks.POTTED_JACARANDA_SAPLING, new Item.Properties()));
        POTTED_PALM_SAPLING = register(func, "potted_palm_sapling", new BlockItem(BOPBlocks.POTTED_PALM_SAPLING, new Item.Properties()));
        POTTED_WILLOW_SAPLING = register(func, "potted_willow_sapling", new BlockItem(BOPBlocks.POTTED_WILLOW_SAPLING, new Item.Properties()));
        POTTED_DEAD_SAPLING = register(func, "potted_dead_sapling", new BlockItem(BOPBlocks.POTTED_DEAD_SAPLING, new Item.Properties()));
        POTTED_MAGIC_SAPLING = register(func, "potted_magic_sapling", new BlockItem(BOPBlocks.POTTED_MAGIC_SAPLING, new Item.Properties()));
        POTTED_UMBRAN_SAPLING = register(func, "potted_umbran_sapling", new BlockItem(BOPBlocks.POTTED_UMBRAN_SAPLING, new Item.Properties()));
        POTTED_HELLBARK_SAPLING = register(func, "potted_hellbark_sapling", new BlockItem(BOPBlocks.POTTED_HELLBARK_SAPLING, new Item.Properties()));
        POTTED_EMPYREAL_SAPLING = register(func, "potted_empyreal_sapling", new BlockItem(BOPBlocks.POTTED_EMPYREAL_SAPLING, new Item.Properties()));
        POTTED_ROSE = register(func, "potted_rose", new BlockItem(BOPBlocks.POTTED_ROSE, new Item.Properties()));
        POTTED_VIOLET = register(func, "potted_violet", new BlockItem(BOPBlocks.POTTED_VIOLET, new Item.Properties()));
        POTTED_LAVENDER = register(func, "potted_lavender", new BlockItem(BOPBlocks.POTTED_LAVENDER, new Item.Properties()));
        POTTED_WHITE_LAVENDER = register(func, "potted_white_lavender", new BlockItem(BOPBlocks.POTTED_WHITE_LAVENDER, new Item.Properties()));
        POTTED_ORANGE_COSMOS = register(func, "potted_orange_cosmos", new BlockItem(BOPBlocks.POTTED_ORANGE_COSMOS, new Item.Properties()));
        POTTED_PINK_DAFFODIL = register(func, "potted_pink_daffodil", new BlockItem(BOPBlocks.POTTED_PINK_DAFFODIL, new Item.Properties()));
        POTTED_PINK_HIBISCUS = register(func, "potted_pink_hibiscus", new BlockItem(BOPBlocks.POTTED_PINK_HIBISCUS, new Item.Properties()));
        POTTED_GLOWFLOWER = register(func, "potted_glowflower", new BlockItem(BOPBlocks.POTTED_GLOWFLOWER, new Item.Properties()));
        POTTED_WILTED_LILY = register(func, "potted_wilted_lily", new BlockItem(BOPBlocks.POTTED_WILTED_LILY, new Item.Properties()));
        POTTED_BURNING_BLOSSOM = register(func, "potted_burning_blossom", new BlockItem(BOPBlocks.POTTED_BURNING_BLOSSOM, new Item.Properties()));
        POTTED_ENDBLOOM = register(func, "potted_endbloom", new BlockItem(BOPBlocks.POTTED_ENDBLOOM, new Item.Properties()));
        POTTED_SPROUT = register(func, "potted_sprout", new BlockItem(BOPBlocks.POTTED_SPROUT, new Item.Properties()));
        POTTED_TINY_CACTUS = register(func, "potted_tiny_cactus", new BlockItem(BOPBlocks.POTTED_TINY_CACTUS, new Item.Properties()));
        POTTED_TOADSTOOL = register(func, "potted_toadstool", new BlockItem(BOPBlocks.POTTED_TOADSTOOL, new Item.Properties()));
        POTTED_GLOWSHROOM = register(func, "potted_glowshroom", new BlockItem(BOPBlocks.POTTED_GLOWSHROOM, new Item.Properties()));
    }

    private static Item register(BiConsumer<ResourceLocation, Item> func, Item item, String name)
    {
        return register(func, name, item);
    }

    private static Item register(BiConsumer<ResourceLocation, Item> func, String name, Item item)
    {
        func.accept(ResourceLocation.fromNamespaceAndPath(BiomesOPlenty.MOD_ID, name), item);
        return item;
    }
}